Repository PolymerLabs/arcs, pull requests merged in 2020-09, with the labels that each got.

#6040 Add error handling for unresolved type in manifest2proto
  src/tools/manifest2proto.ts
  src/tools/tests/manifest2proto-test.ts
Labels: cla: yes

#6049 Try to fix a problem with annotations on schema fields not working. T…
  src/runtime/manifest.ts
  src/runtime/tests/manifest-test.ts
Labels: cla: yes

#6051 Kotlin Paxel Parser
  java/arcs/core/data/expression/Expression.kt
  java/arcs/core/data/expression/PaxelParser.kt
  java/arcs/core/util/Parser.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
  javatests/arcs/core/data/expression/ParserTest.kt
Labels: cla: yes

#6033 Add hooks for storage size related logging.
  java/arcs/android/storage/database/AndroidSqliteDatabaseManager.kt
  java/arcs/core/analytics/Analytics.kt
  java/arcs/core/storage/DriverFactory.kt
  java/arcs/core/storage/database/Database.kt
  java/arcs/core/storage/database/DatabaseManager.kt
  java/arcs/core/storage/driver/Database.kt
  java/arcs/core/storage/driver/Volatile.kt
  java/arcs/jvm/storage/database/testutil/FakeDatabaseManager.kt
  javatests/arcs/android/storage/database/AndroidSqliteDatabaseManagerTest.kt
Labels: cla: yes

#6058 Report the particle state when incorrect in initParticle
  java/arcs/core/host/ParticleContext.kt
Labels: cla: yes

#6061 upgrade to Kotlin 1.4
  WORKSPACE
Labels: cla: yes

#5929 add tests for TypeVariableInfo and AllocatorRecipeResolver (follow up for #5922)
  src/runtime/recipe/internal/handle.ts
  src/tools/tests/allocator-recipe-resolver-test.ts
  src/types/internal/type.ts
  src/types/tests/type-test.ts
Labels: cla: yes

#6059 Fix callbackManager name in DirectStore
  java/arcs/core/storage/DirectStore.kt
Labels: cla: yes

#6069 Adds LET clause for qualified Paxel expressions + various minor fixes
  java/arcs/core/data/expression/Builders.kt
  java/arcs/core/data/expression/Evaluator.kt
  java/arcs/core/data/expression/Expression.kt
  java/arcs/core/data/expression/PaxelParser.kt
  java/arcs/core/data/expression/Serializer.kt
  java/arcs/core/data/expression/Stringifier.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
  javatests/arcs/core/data/expression/ParserTest.kt
Labels: cla: yes

#6037 Pipe devToolsProxy into stores
  java/arcs/android/devtools/DevToolsService.kt
  java/arcs/android/storage/service/BindingContext.kt
  java/arcs/android/storage/service/DevToolsProxyImpl.kt
  java/arcs/android/storage/service/IDevToolsProxy.aidl
  java/arcs/core/storage/DevToolsProxy.kt
  java/arcs/core/storage/ReferenceModeStore.kt
  java/arcs/core/storage/Store.kt
  java/arcs/core/storage/StoreManager.kt
  java/arcs/sdk/android/storage/ServiceStore.kt
  java/arcs/sdk/android/storage/service/StorageService.kt
  javatests/arcs/android/storage/ReferenceModeStoreDatabaseImplIntegrationTest.kt
  javatests/arcs/android/storage/service/BindingContextTest.kt
  javatests/arcs/core/storage/ReferenceModeStoreDatabaseIntegrationTest.kt
  javatests/arcs/core/storage/ReferenceModeStoreStabilityTest.kt
  javatests/arcs/core/storage/ReferenceModeStoreTest.kt
  javatests/arcs/core/storage/ReferenceTest.kt
  javatests/arcs/core/storage/StoreTest.kt
  javatests/arcs/core/storage/StoreWriteBackTest.kt
Labels: cla: yes

#6066 Increase delay in PerformanceStatisticsTest to prevent flakes
  javatests/arcs/core/util/performance/PerformanceStatisticsTest.kt
Labels: cla: yes

#6068 fix support for schema field annotations in manifest
  src/runtime/manifest.ts
  src/runtime/tests/manifest-test.ts
Labels: cla: yes

#6063 pass annotations for reference fields to the EntityRef kotlin class. …
  java/arcs/core/data/BUILD
  java/arcs/core/data/SchemaFields.kt
  src/runtime/canonical-manifest.ts
  src/runtime/tests/manifest-parser-test.ts
  src/tools/annotation2proto.ts
  src/tools/annotations-utils.ts
  src/tools/kotlin-schema-generator.ts
  src/tools/manifest2proto.ts
  src/tools/plan-generator.ts
  src/tools/policy2proto.ts
  src/tools/schema2kotlin.ts
  src/tools/tests/annotations-utils-test.ts
  src/tools/tests/goldens/generated-schemas.jvm.kt
  src/tools/tests/goldens/kotlin-schema-generation.cgtest
  src/tools/tests/goldens/kt_generated-schemas.jvm.kt
Labels: cla: yes

#6073 Associated a bug with a TODO in fixpoint iterator.
  java/arcs/core/analysis/RecipeGraphFixpointIterator.kt
Labels: cla: yes

#6076 Sends Paxel expression string from TS Parser to Kotlin
  java/arcs/core/data/HandleConnectionSpec.kt
  java/arcs/core/data/Recipe.kt
  java/arcs/core/data/expression/Serializer.kt
  java/arcs/core/data/proto/ParticleSpecProtoDecoder.kt
  javatests/arcs/core/data/RecipeTest.kt
  javatests/arcs/core/data/proto/BUILD
  javatests/arcs/core/data/proto/ParticleSpecProtoDecoderTest.kt
  javatests/arcs/showcase/expression/expression.arcs
  src/runtime/manifest-parser.pegjs
  src/runtime/manifest.ts
  src/runtime/tests/manifest-parser-test.ts
  src/runtime/tests/manifest-test.ts
  src/tools/kotlin-generation-utils.ts
  src/tools/plan-generator.ts
  src/tools/tests/goldens/plan-generator-handleConnections.cgtest
  src/tools/tests/manifest2proto-test.ts
Labels: cla: yes

#6077 Uses PaxelParser in Paxel Showcase and EvaluatorParticle Test.
  javatests/arcs/core/data/expression/EvaluatorParticleTest.kt
  javatests/arcs/core/data/expression/Particles.arcs
  javatests/arcs/showcase/expression/ExpressionShowcaseTest.kt
  src/runtime/tests/manifest-parser-test.ts
Labels: cla: yes

#6060 Add support for callbacks on DirectStoreMuxer
  java/arcs/core/storage/DirectStoreMuxer.kt
  java/arcs/core/storage/ProxyInterface.kt
  java/arcs/core/storage/ReferenceModeStore.kt
  javatests/arcs/core/storage/DirectStoreMuxerTest.kt
  javatests/arcs/core/storage/RamDiskDirectStoreMuxerIntegrationTest.kt
Labels: cla: yes

#6079 add ident.ident lookup in refinement expressions in paxel mode
  src/runtime/manifest-parser.pegjs
  src/runtime/tests/manifest-parser-test.ts
Labels: cla: yes

#6080 Specifies EvaluatorParticle as a location for Paxel particles and cleans up Paxel showcase.
  java/arcs/core/data/Recipe.kt
  javatests/arcs/core/data/BUILD
  javatests/arcs/core/data/RecipeTest.kt
  javatests/arcs/showcase/expression/ExpressionShowcaseTest.kt
  javatests/arcs/showcase/expression/expression.arcs
  src/tools/plan-generator.ts
  src/tools/tests/goldens/plan-generator-particles.cgtest
Labels: cla: yes

#6072 Suppress the exception due to missing scope
  java/arcs/core/storage/DirectStore.kt
Labels: cla: yes

#6086 Remove @Synchronized (KotlinJS not compatible)
  java/arcs/core/host/SimpleSchedulerProvider.kt
  java/arcs/core/storage/StorageKeyParser.kt
Labels: cla: yes

#6085 Remove Java exceptions in favor of Kotlin (multiplatform) exceptions
  java/arcs/core/data/expression/Evaluator.kt
  java/arcs/core/entity/Handle.kt
Labels: cla: yes

#6087 Add multiplatform version of java.io.Closeable
  java/arcs/core/storage/BUILD
  java/arcs/core/storage/ProxyInterface.kt
  java/arcs/core/storage/RawEntityDereferencer.kt
  java/arcs/core/util/Closeable.kt
Labels: cla: yes

#6088 .javaClass doesn't exist in JS, use ::class instead
  java/arcs/core/storage/Reference.kt
Labels: cla: yes

#6074 Remove console noise from unit tests.
  src/planning/tests/planner-test.ts
  src/runtime/testing/sequence.ts
  src/runtime/testing/tests/sequence-test.ts
  src/runtime/tests/artifacts/Products/source/ShowProduct.js
  src/runtime/tests/description-test.ts
  src/runtime/tests/manifest-test.ts
  src/testing/test-util.ts
  src/tests/particles/products-test.ts
  src/types/tests/refiner-test.ts
  src/types/tests/schema-test.ts
Labels: cla: yes

#4893 Refinement from query code generation
  src/types/internal/refiner.ts
  src/types/internal/schema.ts
  src/types/tests/refiner-test.ts
  src/utils/internal/hot.ts
  src/utils/lib-utils.ts
Labels: cla: yes

#6090 Test refinement scoping for field names and ensure source locations are attached
  src/runtime/manifest-parser.pegjs
  src/runtime/manifest.ts
  src/runtime/tests/manifest-test.ts
Labels: cla: yes

#6075 Move more standalone classes and functions into utils.
  src/planning/plan/tests/planificator-test.ts
  src/runtime/api-channel.ts
  src/runtime/arc.ts
  src/runtime/bytes.ts
  src/runtime/particle-execution-host.ts
  src/runtime/policy/tests/policy-parser-test.ts
  src/runtime/policy/tests/policy-test.ts
  src/runtime/storage/direct-store-muxer.ts
  src/runtime/storage/direct-store.ts
  src/runtime/storage/reference-mode-store.ts
  src/runtime/storage/storage-proxy-muxer.ts
  src/runtime/storage/store-interface.ts
  src/runtime/storage/tests/store-test.ts
  src/runtime/tests/bytes-test.ts
  src/runtime/tests/field-path-test.ts
  src/runtime/tests/wasm-test.ts
  src/runtime/wasm.ts
  src/tools/manifest2proto.ts
  src/tools/policy2proto.ts
  src/tools/schema2graph.ts
  src/tools/tests/manifest2proto-test.ts
  src/utils/internal/bimap.ts
  src/utils/internal/misc.ts
  src/utils/internal/mutex.ts
  src/utils/lib-utils.ts
  src/utils/tests/bimap-test.ts
  src/utils/tests/misc-test.ts
  src/utils/tests/mutex-test.ts
Labels: cla: yes

#6057 Fixing `arcs_kt_gen` dependency system for G3
  third_party/java/arcs/build_defs/internal/kotlin.bzl
Labels: cla: yes

#6052 Added `init` block to register schemas on creation.
  java/arcs/core/data/Schema.kt
Labels: cla: yes

#6082 Updates to KT JSON
  java/arcs/core/util/Json.kt
  javatests/arcs/core/util/JsonTest.kt
Labels: cla: yes

#6039 Improvements to Bazel rule organization, and a showcase of manifest imports.
  javatests/arcs/showcase/imports/BUILD
  javatests/arcs/showcase/imports/ImportsTest.kt
  javatests/arcs/showcase/imports/README.md
  javatests/arcs/showcase/imports/particles/AcceptImports.kt
  javatests/arcs/showcase/imports/particles/BUILD
  javatests/arcs/showcase/imports/particles/IngestDock.kt
  javatests/arcs/showcase/imports/particles/port.arcs
  javatests/arcs/showcase/imports/recipes/BUILD
  javatests/arcs/showcase/imports/recipes/gather_imports.arcs
  javatests/arcs/showcase/imports/schemas/BUILD
  javatests/arcs/showcase/imports/schemas/common.arcs
  javatests/arcs/showcase/imports/schemas/shipping.arcs
  third_party/java/arcs/build_defs/internal/gen.bzl
  third_party/java/arcs/build_defs/internal/rules.bzl
  third_party/java/arcs/build_defs/internal/schemas.bzl
  third_party/java/arcs/build_defs/internal/tools.oss.bzl
Labels: cla: yes, timezonegame

#6095 Make ts imports consistent in the github code base.
  src/tools/dev_server/hot-reload-server.ts
  src/tools/language-server/util.ts
  src/tools/vscode-language-client/src/workspace.ts
Labels: cla: yes

#6084 Remove boolean return value from `onProxyMessage`
  java/arcs/android/storage/service/BindingContext.kt
  java/arcs/core/storage/ActiveStore.kt
  java/arcs/core/storage/DirectStore.kt
  java/arcs/core/storage/DirectStoreMuxer.kt
  java/arcs/core/storage/ProxyInterface.kt
  java/arcs/core/storage/ReferenceModeStore.kt
  java/arcs/sdk/android/storage/ServiceStore.kt
  javatests/arcs/android/storage/ReferenceModeStoreDatabaseImplIntegrationTest.kt
  javatests/arcs/android/storage/service/BindingContextTest.kt
  javatests/arcs/core/storage/RamDiskDirectStoreMuxerIntegrationTest.kt
  javatests/arcs/core/storage/RamDiskStoreIntegrationTest.kt
  javatests/arcs/core/storage/ReferenceModeStoreDatabaseIntegrationTest.kt
  javatests/arcs/core/storage/ReferenceModeStoreTest.kt
  javatests/arcs/core/storage/ReferenceTest.kt
  javatests/arcs/core/storage/StoreEndpointFake.kt
  javatests/arcs/core/storage/StoreTest.kt
Labels: cla: yes

#6098 paxel parser allows functionCall(args).field
  java/arcs/core/data/expression/Evaluator.kt
  java/arcs/core/data/expression/PaxelParser.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
  javatests/arcs/core/data/expression/ParserTest.kt
Labels: cla: yes

#6097 parse functionCall(args).field in TS
  src/runtime/manifest-ast-types/manifest-ast-nodes.ts
  src/runtime/manifest-parser.pegjs
  src/runtime/tests/manifest-parser-test.ts
Labels: cla: yes

#6093 Remove unused method and fix docs.
  java/arcs/core/storage/DriverFactory.kt
  java/arcs/core/storage/driver/Volatile.kt
Labels: cla: yes

#6089 Tests demonstrating that schema upgrades are viable.
  javatests/arcs/android/storage/database/DatabaseImplTest.kt
Labels: cla: yes

#6099 Cleans up EvaluatorParticleTest
  javatests/arcs/core/data/expression/EvaluatorParticleTest.kt
  javatests/arcs/core/data/expression/ParserTest.kt
  javatests/arcs/core/data/expression/Particles.arcs
Labels: cla: yes

#6102 Tests that reproduce schema alias brokenness, and the impact of this on DB writes.
  javatests/arcs/android/storage/database/DatabaseImplTest.kt
  src/types/tests/schema-test.ts
Labels: cla: yes

#6096 DevTools Message Updates
  java/arcs/android/devtools/DevToolsMessage.kt
  java/arcs/android/devtools/DevToolsService.kt
  java/arcs/android/devtools/RawDevToolsMessage.kt
  java/arcs/android/devtools/StoreSyncMessage.kt
Labels: cla: yes

#6071 Make the `off` method of stores suspending.
  java/arcs/core/storage/ActiveStore.kt
  java/arcs/core/storage/DirectStorageEndpointManager.kt
  java/arcs/core/storage/DirectStore.kt
  java/arcs/core/storage/ProxyInterface.kt
  java/arcs/core/storage/RawEntityDereferencer.kt
  java/arcs/core/storage/ReferenceModeStore.kt
  java/arcs/core/storage/util/OperationQueue.kt
  java/arcs/core/storage/util/SimpleQueue.kt
  java/arcs/sdk/android/storage/ServiceStore.kt
  javatests/arcs/core/storage/StoreEndpointFake.kt
Labels: cla: yes

#6107 Allow Paxel let expression in the peg parser
  src/runtime/manifest-ast-types/manifest-ast-nodes.ts
  src/runtime/manifest-parser.pegjs
  src/runtime/tests/manifest-parser-test.ts
Labels: cla: yes

#6108 Teaches Paxel that functions can return null
  java/arcs/core/data/expression/Builders.kt
  java/arcs/core/data/expression/Evaluator.kt
  java/arcs/core/data/expression/Expression.kt
  java/arcs/core/data/expression/RawEntityScope.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
Labels: cla: yes

#6091 Add an hard reference boolean field to references. This is set by Ent…
  java/arcs/android/crdt/ReferenceProto.kt
  java/arcs/android/crdt/referencable.proto
  java/arcs/android/storage/database/DatabaseImpl.kt
  java/arcs/core/data/SchemaFields.kt
  java/arcs/core/entity/EntityBase.kt
  java/arcs/core/entity/Reference.kt
  java/arcs/core/storage/Reference.kt
  javatests/arcs/android/crdt/ReferenceProtoTest.kt
  javatests/arcs/android/entity/BUILD
  javatests/arcs/android/entity/HardReferenceTest.kt
  javatests/arcs/android/entity/test.arcs
  javatests/arcs/android/storage/database/DatabaseImplTest.kt
  javatests/arcs/android/storage/database/DatabaseUpgradeTest.kt
  javatests/arcs/core/data/SchemaFieldsTest.kt
  javatests/arcs/core/entity/DummyEntity.kt
  javatests/arcs/core/entity/EntityBaseTest.kt
  javatests/arcs/sdk/spec/ReferenceSpecTest.kt
  javatests/arcs/sdk/spec/reference.arcs
Labels: cla: yes

#6101 Rename a couple of test files to -test.ts instead of -tests.ts
  src/common/time/tests/instant-test.ts
  src/tools/tests/plan-generator-test.ts
Labels: cla: yes

#6110 Adds a null-safe lookup (?.) operator to Paxel
  java/arcs/core/data/expression/Builders.kt
  java/arcs/core/data/expression/Evaluator.kt
  java/arcs/core/data/expression/Expression.kt
  java/arcs/core/data/expression/PaxelParser.kt
  java/arcs/core/data/expression/Serializer.kt
  java/arcs/core/data/expression/Stringifier.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
  javatests/arcs/core/data/expression/ParserTest.kt
  src/runtime/manifest-parser.pegjs
  src/runtime/tests/manifest-parser-test.ts
Labels: cla: yes

#6100 Prohibit importing internal files from other modules in our custom loader
  src/crdt/tests/crdt-collection-test.ts
  src/crdt/tests/crdt-count-test.ts
  src/crdt/tests/crdt-entity-test.ts
  src/crdt/tests/crdt-singleton-test.ts
  tools/custom-loader.mjs
  tools/sigh.ts
  tsconfig.json
Labels: cla: yes

#6078 Improvements to `runOnAllDatabases`: run all jobs & test
  java/arcs/android/storage/database/AndroidSqliteDatabaseManager.kt
  java/arcs/core/common/CompositeException.kt
  java/arcs/core/storage/database/BUILD
  java/arcs/core/storage/database/DatabaseManager.kt
  java/arcs/jvm/storage/database/testutil/FakeDatabaseManager.kt
  javatests/arcs/core/storage/database/BUILD
  javatests/arcs/core/storage/database/DatabaseManagerTest.kt
Labels: cla: yes

#6114 Elvis operator and null literal for Paxel
  java/arcs/core/data/expression/Builders.kt
  java/arcs/core/data/expression/Evaluator.kt
  java/arcs/core/data/expression/Expression.kt
  java/arcs/core/data/expression/PaxelParser.kt
  java/arcs/core/data/expression/Serializer.kt
  java/arcs/core/data/expression/Stringifier.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
  src/runtime/manifest-ast-types/manifest-ast-nodes.ts
  src/runtime/manifest-parser.pegjs
  src/runtime/tests/manifest-parser-test.ts
Labels: cla: yes

#6115 Allow line breaks in refinements and paxel expressions
  src/runtime/manifest-parser.pegjs
  src/runtime/tests/manifest-parser-test.ts
Labels: cla: yes

#6111 Add StoreMessage to DevTools.
  java/arcs/android/devtools/BUILD
  java/arcs/android/devtools/DevToolsMessage.kt
  java/arcs/android/devtools/DevToolsService.kt
  java/arcs/android/devtools/StoreMessage.kt
Labels: cla: yes

#6104 Ensure that schema hashes don't collide in a couple of different cases:
  java/arcs/core/data/testdata/Manifest2ProtoTest.binarypb
  java/arcs/core/data/testdata/Manifest2ProtoTest.textproto
  src/devtools-connector/tests/arc-stores-fetcher-test.ts
  src/tools/tests/goldens/WriterReaderExample.kt
  src/tools/tests/goldens/generated-from-kotlin.jvm.kt
  src/tools/tests/goldens/generated-schemas.h
  src/tools/tests/goldens/generated-schemas.jvm.kt
  src/tools/tests/goldens/kotlin-entity-class.cgtest
  src/tools/tests/goldens/kotlin-schema-generation.cgtest
  src/tools/tests/goldens/kotlin-type-generator.cgtest
  src/tools/tests/goldens/kt_generated-schemas.jvm.kt
  src/tools/tests/goldens/plan-generator-handleConnections.cgtest
  src/tools/tests/goldens/plan-generator-handles.cgtest
  src/tools/tests/goldens/plan-generator-plans.cgtest
  src/tools/tests/manifest2proto-test.ts
  src/tools/tests/recipe2plan-test.ts
  src/types/internal/schema.ts
  src/types/tests/schema-test.ts
Labels: cla: yes

#6119 Reorganize the Slots API for recipes.
  src/planning/strategies/match-recipe-by-verb.ts
  src/runtime/arcs-types/particle-spec.ts
  src/runtime/manifest.ts
  src/runtime/recipe/internal/particle.ts
  src/runtime/recipe/internal/recipe-interface.ts
  src/runtime/recipe/internal/recipe-walker.ts
  src/runtime/recipe/internal/slot-connection.ts
  src/runtime/relevance.ts
  src/runtime/tests/manifest-test.ts
Labels: cla: yes

#6120 Improve type tracking through recipe.updateToClone.
  src/planning/strategies/convert-constraints-to-connections.ts
  src/planning/strategies/match-recipe-by-verb.ts
  src/runtime/recipe/internal/recipe-interface.ts
  src/runtime/recipe/internal/recipe.ts
Labels: cla: yes

#6070 declare SchemaField class to replace the unstructured object
  src/dataflow/analysis/particle-node.ts
  src/runtime/entity-utils.ts
  src/runtime/entity.ts
  src/runtime/field-path.ts
  src/runtime/manifest-ast-types/manifest-ast-nodes.ts
  src/runtime/manifest.ts
  src/runtime/manual_tests/loader-test.ts
  src/runtime/policy/ingress-validation.ts
  src/runtime/policy/policy.ts
  src/runtime/storage/tests/reference-mode-store-integration-test.ts
  src/runtime/tests/manifest-test.ts
  src/runtime/wasm.ts
  src/tools/kotlin-schema-field.ts
  src/tools/kotlin-schema-generator.ts
  src/tools/manifest2proto.ts
  src/tools/schema2cpp.ts
  src/tools/schema2graph.ts
  src/types/internal/schema-field.ts
  src/types/internal/schema-from-literal.ts
  src/types/internal/schema.ts
  src/types/lib-types.ts
  src/types/tests/schema-test.ts
  src/types/tests/type-test.ts
  src/wasm/tests/wasm-api-test.ts
Labels: cla: yes

#6121 Treat absence of '@policy' as error only if recipe has egresses.
  java/arcs/tools/VerifyPolicy.kt
Labels: cla: yes

#6118 Update pinned maven dependencies
  maven_install.json
Labels: cla: yes

#6116 Allow equality operators on nulls in Paxel
  java/arcs/core/data/expression/Builders.kt
  java/arcs/core/data/expression/Expression.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
Labels: cla: yes

#6126 Show parsed JSON messages in DevToolsNG UI
  devtoolsNG/basic/index.html
Labels: cla: yes

#6123 Add notes about usage of `runBlocking` on periodic tasks
  java/arcs/android/storage/database/DatabaseGarbageCollectionPeriodicTask.kt
  java/arcs/android/storage/ttl/PeriodicCleanupTask.kt
Labels: cla: yes

#5894 Make the register/unregisterCallback calls in StorageService non-blocking
  java/arcs/android/storage/service/BindingContext.kt
  java/arcs/android/storage/service/DeferredResult.kt
  java/arcs/android/storage/service/IRegistrationCallback.aidl
  java/arcs/android/storage/service/IStorageService.aidl
  java/arcs/android/storage/service/SuspendingServiceMethods.kt
  java/arcs/sdk/android/storage/ServiceStore.kt
  javatests/arcs/android/storage/service/BUILD
  javatests/arcs/android/storage/service/BindingContextTest.kt
  javatests/arcs/android/storage/service/DeferredResultTest.kt
  javatests/arcs/android/storage/service/StorageServiceManagerTest.kt
  javatests/arcs/sdk/android/storage/service/StorageServiceConnectionTest.kt
  javatests/arcs/sdk/android/storage/service/StorageServiceTest.kt
Labels: cla: yes

#6122 Add a second constructor for JsonObjects
  java/arcs/android/devtools/StoreMessage.kt
  java/arcs/core/util/Json.kt
  javatests/arcs/core/util/JsonTest.kt
Labels: cla: yes

#6062 Upgrading Kotlin-Native compiler rules to 1.4.0
  build_defs/kotlin_native/build_defs.bzl
  build_defs/kotlin_native/kotlinc_wrapper.sh
  build_defs/kotlin_native/repo.bzl
  third_party/java/arcs/build_defs/internal/kotlin.bzl
Labels: cla: yes

#6117 schema2graph: Track added fields to be used when generating interfaces
  src/tools/schema2graph.ts
  src/tools/tests/schema2graph-test.ts
Labels: cla: yes

#6106 Entity mutation in typescript
  src/crdt/internal/crdt-entity.ts
  src/crdt/internal/crdt-singleton.ts
  src/crdt/tests/crdt-entity-test.ts
  src/runtime/storage/handle.ts
  src/runtime/storage/tests/handle-test.ts
  src/runtime/storage/tests/reference-mode-store-test.ts
Labels: cla: yes

#6135 Remove unnecessary type annotation
  src/planning/strategies/convert-constraints-to-connections.ts
Labels: cla: yes

#6136 I don't think we need this any more.
  src/runtime/flags.ts
Labels: cla: yes

#6134 declare storage-service API and delegate PEH calls to it
  src/devtools-connector/arc-stores-fetcher.ts
  src/planning/plan/tests/plan-producer-test.ts
  src/planning/plan/tests/planificator-test.ts
  src/planning/plan/tests/replan-queue-test.ts
  src/planning/recipe-index.ts
  src/planning/strategies/tests/convert-constraints-to-connections-test.ts
  src/planning/strategies/tests/find-hosted-particle-test.ts
  src/planning/strategies/tests/init-population-test.ts
  src/planning/strategies/tests/map-slots-test.ts
  src/planning/testing/strategy-test-helper.ts
  src/planning/tests/planner-test.ts
  src/planning/tests/recipe-index-test.ts
  src/planning/tests/speculator-test.ts
  src/runtime/arc.ts
  src/runtime/particle-execution-host.ts
  src/runtime/runtime.ts
  src/runtime/storage/storage-service.ts
  src/runtime/storage/store.ts
  src/runtime/testing/manifest-integration-test-setup.ts
  src/runtime/tests/arc-test.ts
  src/runtime/tests/data-layer-test.ts
  src/runtime/tests/description-test.ts
  src/runtime/tests/multiplexer-test.ts
  src/runtime/tests/particle-api-test.ts
  src/runtime/tests/particle-interface-loading-test.ts
  src/runtime/tests/particle-interface-loading-with-slots-test.ts
  src/runtime/tests/recipe-resolver-test.ts
  src/runtime/tests/runtime-test.ts
  src/tests/hotreload-integration-test.ts
  src/tests/particles/products-test.ts
  src/tests/slot-composer-test.ts
  src/wasm/tests/wasm-api-test.ts
Labels: cla: yes

#6137 Fix DevTools parsing of clock and clean up constants.
  java/arcs/android/devtools/DevToolsMessage.kt
  java/arcs/android/devtools/StoreMessage.kt
  java/arcs/android/devtools/StoreSyncMessage.kt
Labels: cla: yes

#6127 Fixes E2E app by registering a Volatile Driver
  javatests/arcs/android/e2e/testapp/TestApplication.kt
Labels: cla: yes

#6133 Allow subclass to override worker classes so we can have customized Worker implementation which also does logging in google3.
  java/arcs/sdk/android/storage/service/StorageService.kt
Labels: cla: yes

#5858 Removed ActiveMuxer
  src/runtime/storage/direct-store-muxer.ts
  src/runtime/storage/storage.ts
  src/runtime/storage/store-interface.ts
  src/runtime/storage/store.ts
  src/runtime/tests/arc-test.ts
Labels: cla: yes

#6140 replace wasm.ts dependency on particle-execution-context with channel-constructor
  src/runtime/reference.ts
  src/runtime/wasm.ts
Labels: cla: yes

#6124 Remove usage of `runBlocking` from AbstractArcHost
  java/arcs/core/host/AbstractArcHost.kt
  javatests/arcs/android/e2e/testapp/PersonHostService.kt
  javatests/arcs/android/e2e/testapp/WriteAnimalHostService.kt
  javatests/arcs/core/allocator/AllocatorTestBase.kt
  javatests/arcs/core/host/AbstractArcHostTest.kt
  javatests/arcs/core/host/TestingHost.kt
  javatests/arcs/showcase/ShowcaseEnvironment.kt
Labels: cla: yes

#6142 Add funcs to get entity count, storage size and is storage too large …
  java/arcs/core/storage/DriverFactory.kt
Labels: cla: yes

#6144 refactor particle-execution-context: declare storage-frontend interface and storage-endpoint implementation classes
  src/runtime/particle-execution-context.ts
  src/runtime/storage/storage-endpoint.ts
  src/runtime/storage/storage-frontend.ts
Labels: cla: yes

#6125 Bugfix to a subtle field lookup bug
  java/arcs/core/data/expression/Builders.kt
  java/arcs/core/data/expression/Evaluator.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
Labels: cla: yes

#6113 Introduce a way of creating foreign references (references not pointi…
  java/arcs/core/entity/EntityDereferencerFactory.kt
  java/arcs/core/entity/ForeignReferenceChecker.kt
  java/arcs/core/host/EntityHandleManager.kt
  java/arcs/core/storage/api/DriverAndKeyConfigurator.kt
  java/arcs/core/storage/keys/ForeignStorageKey.kt
  javatests/arcs/android/entity/DifferentAndroidHandleManagerDifferentStoresTest.kt
  javatests/arcs/android/entity/DifferentHandleManagerTest.kt
  javatests/arcs/android/entity/HardReferenceTest.kt
  javatests/arcs/android/entity/SameHandleManagerTest.kt
  javatests/arcs/android/entity/test.arcs
  javatests/arcs/core/entity/DifferentHandleManagerDifferentStoresTest.kt
  javatests/arcs/core/entity/DifferentHandleManagerTest.kt
  javatests/arcs/core/entity/ForeignReferenceCheckerTest.kt
  javatests/arcs/core/entity/HandleManagerTestBase.kt
  javatests/arcs/core/entity/SameHandleManagerTest.kt
  javatests/arcs/core/entity/StorageAdapterTest.kt
  javatests/arcs/core/entity/test.arcs
  javatests/arcs/core/storage/keys/BUILD
  javatests/arcs/core/storage/keys/ForeignStorageKeyTest.kt
Labels: cla: yes

#6143 immutable scopes + orderby
  java/arcs/core/data/expression/Builders.kt
  java/arcs/core/data/expression/Evaluator.kt
  java/arcs/core/data/expression/Expression.kt
  java/arcs/core/data/expression/PaxelParser.kt
  java/arcs/core/data/expression/RawEntityScope.kt
  java/arcs/core/data/expression/Serializer.kt
  java/arcs/core/data/expression/Stringifier.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
  javatests/arcs/core/data/expression/ParserTest.kt
Labels: cla: yes

#6146 Fix a race condition during particle shutdown
  java/arcs/core/entity/BaseHandle.kt
  java/arcs/core/entity/Handle.kt
  java/arcs/core/host/ParticleContext.kt
  java/arcs/core/host/api/HandleHolder.kt
  java/arcs/sdk/Particle.kt
  javatests/arcs/core/host/ParticleContextTest.kt
Labels: cla: yes

#6128 Remove the `snapshotAsync` method from PerformanceStatistics.
  java/arcs/core/util/performance/PerformanceStatistics.kt
  javatests/arcs/core/util/performance/PerformanceStatisticsTest.kt
Labels: cla: yes

#6147 remove deprecated method ReinstantiateParticle api-channel
  src/runtime/api-channel.ts
  src/runtime/arc.ts
  src/runtime/particle-execution-context.ts
  src/runtime/particle-execution-host.ts
  src/runtime/tests/api-channel-test.ts
Labels: cla: yes

#6148 PaxelParser supports field access of nested expressions
  java/arcs/core/data/expression/PaxelParser.kt
  javatests/arcs/core/data/expression/ParserTest.kt
Labels: cla: yes

#6150 Make sure the correct error gets reported during manifest parsing.
  src/runtime/manifest.ts
  src/runtime/tests/manifest-test.ts
Labels: cla: yes

#6151 Change AST representations for Particle to match output of parser.
  package.json
  src/runtime/manifest-ast-types/manifest-ast-nodes.ts
  src/runtime/manifest-parser.pegjs
Labels: cla: yes

#6081 Remove `runBlocking` from the `sendProxyMessage` service call.
  java/arcs/android/storage/service/BindingContext.kt
  java/arcs/core/common/BUILD
  java/arcs/core/common/CounterFlow.kt
  javatests/arcs/android/storage/service/BindingContextTest.kt
  javatests/arcs/core/entity/HandleManagerTestBase.kt
  javatests/arcs/sdk/android/storage/service/StorageServiceTest.kt
Labels: cla: yes

#6149 Minor fixes in DevTools.
  java/arcs/android/devtools/DevToolsMessage.kt
  java/arcs/android/devtools/StoreMessage.kt
Labels: cla: yes

#6153 sum() aggregation function for Paxel
  java/arcs/core/data/expression/Builders.kt
  java/arcs/core/data/expression/Evaluator.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
  javatests/arcs/core/data/expression/ParserTest.kt
  src/runtime/manifest-ast-types/manifest-ast-nodes.ts
Labels: cla: yes

#6157 Removed StoreMuxer
  src/runtime/api-channel.ts
  src/runtime/particle-execution-host.ts
  src/runtime/storage/storage-service.ts
  src/runtime/storage/storage.ts
  src/runtime/storage/store.ts
  src/runtime/storage/tests/direct-store-muxer-test.ts
  src/runtime/storage/tests/ramdisk-direct-store-muxer-integration-test.ts
Labels: cla: yes

#6158 Fixes sha256 of Kotlin native mac package
  build_defs/kotlin_native/repo.bzl
Labels: cla: yes

#6152 Refactor Arc and Manifest store related data structs
  src/devtools-connector/arc-stores-fetcher.ts
  src/planning/strategies/tests/find-hosted-particle-test.ts
  src/planning/tests/planner-test.ts
  src/runtime/arc-serializer.ts
  src/runtime/arc.ts
  src/runtime/manifest.ts
  src/runtime/storage/tests/entity-handle-factory-test.ts
  src/runtime/tests/arc-test.ts
  src/runtime/tests/data-layer-test.ts
  src/runtime/tests/manifest-test.ts
  src/runtime/tests/particle-api-more-test.ts
  src/runtime/tests/particle-interface-loading-test.ts
  src/tests/arc-integration-test.ts
  src/tests/multiplexer-integration-test.ts
  src/tests/particles/common-test.ts
  src/wasm/tests/wasm-api-test.ts
Labels: cla: yes

#6155 Fix a race condition in CounterFlow
  java/arcs/core/common/CounterFlow.kt
  javatests/arcs/core/common/BUILD
  javatests/arcs/core/common/CounterFlowTest.kt
Labels: cla: yes

#6132 Remove HandleHolderBase.awaitReady
  java/arcs/sdk/Particle.kt
  javatests/arcs/showcase/inline/Reader.kt
  javatests/arcs/showcase/inline/Writer.kt
  javatests/arcs/showcase/references/Reader.kt
  javatests/arcs/showcase/references/Writer.kt
Labels: cla: yes

#6162 Grammar changes to README
  java/arcs/tools/README.md
Labels: cla: yes, ready to pull

#6156 fix particlestate not being deserialized correctly
  java/arcs/core/host/ArcHostContextParticle.kt
  java/arcs/core/host/ArcState.kt
  java/arcs/core/host/EntityHandleManager.kt
  java/arcs/core/host/HandleManager.kt
  java/arcs/core/host/ParticleContext.kt
  javatests/arcs/core/allocator/AllocatorTestBase.kt
Labels: cla: yes, ready to pull

#6171 Lint fixes
  java/arcs/core/host/ArcHostContextParticle.kt
  java/arcs/core/host/ArcState.kt
Labels: cla: yes, ready to pull

#6160 Initial add of DevToolsProxy to DirectStore.
  java/arcs/android/devtools/DevToolsService.kt
  java/arcs/android/storage/service/DevToolsProxyImpl.kt
  java/arcs/android/storage/service/IDevToolsProxy.aidl
  java/arcs/core/storage/DevToolsProxy.kt
  java/arcs/core/storage/DirectStore.kt
  java/arcs/core/storage/DirectStoreMuxer.kt
  java/arcs/core/storage/ReferenceModeStore.kt
  java/arcs/core/storage/Store.kt
  javatests/arcs/core/storage/DirectStoreMuxerTest.kt
  javatests/arcs/core/storage/RamDiskDirectStoreMuxerIntegrationTest.kt
  javatests/arcs/core/storage/RamDiskStoreIntegrationTest.kt
Labels: cla: yes, ready to pull

#6138 Factor manifest-primitive-parser (low-level AST generation) into its own module
  src/runtime/manifest-ast-types/manifest-ast-nodes.ts
  src/runtime/manifest-primitive-parser/manifest-primitive-parser.ts
  src/runtime/manifest-primitive-parser/tests/manifest-primitive-parser-test.ts
  src/runtime/manifest-primitive-parser/tools/README.md
  src/runtime/manifest-primitive-parser/tools/playground.html
Labels: cla: yes, ready to pull

#6183 Update wdio-chromedriver-service for Chrome 83
  .gitignore
  package.json
  shells/tests/wdio.conf.js
Labels: cla: yes

#6207 Wrap RamDisk.clear() in runBlocking
  javatests/arcs/android/e2e/testapp/TestApplication.kt
Labels: cla: yes, ready to pull, timezonegame

#6209 Wrap DemoApplication's call to RamDisk.clear in runBlocking
  java/arcs/android/demo/DemoApplication.kt
Labels: cla: yes, ready to pull

#6173 Cleaned up Main README for project
  AUTHORS.md
  CONTRIBUTING.md
  README.md
  docs/logo.png
  src/wasm/cpp/README.md
  tools/README.md
  tools/setup
Labels: cla: yes, ready to pull

#6261 Using Github Actions to deploy to arcs-live.
  .github/workflows/live-deploy.yml
  README.md
Labels: cla: yes, ready to pull

#6266 Fixing arcs-live deploy
  .github/workflows/live-deploy.yml
  README.md
  tools/deploy
Labels: cla: yes

#6278 Update Robolectric from 4.1 to 4.4
  WORKSPACE
  maven_install.json
Labels: cla: yes

#6277 Updating parts of the arcs-live deployment process
  tools/deployment/.gitignore
Labels: cla: yes, ready to pull
