Repository PolymerLabs/arcs, pull requests merged in 2020-08, with the labels that each got.

#5842 Register schemas that are encountered when decoding protos.
  java/arcs/core/data/proto/TypeProtoDecoders.kt
  javatests/arcs/core/data/proto/TypeProtoDecodersTest.kt
Labels: cla: yes

#5841 Define an `@policy` annotation for recipes
  java/arcs/core/data/Annotation.kt
  java/arcs/core/data/Recipe.kt
  javatests/arcs/core/data/RecipeTest.kt
  src/runtime/canonical-manifest.ts
  src/runtime/manifest.ts
  src/runtime/recipe/recipe.ts
  src/runtime/tests/manifest-test.ts
  src/tools/tests/manifest2proto-test.ts
Labels: cla: yes

#5840 Convert most of the rest of the plan-generator-tests into cgtest format.
  src/tools/tests/codegen-unit-test-base.ts
  src/tools/tests/codegen-unit-tests-runner-test.ts
  src/tools/tests/codegen-unit-tests-updater.ts
  src/tools/tests/goldens/plan-generator-handleConnections.cgtest
  src/tools/tests/goldens/plan-generator-handles.cgtest
  src/tools/tests/goldens/plan-generator-particles.cgtest
  src/tools/tests/goldens/plan-generator-plans.cgtest
  src/tools/tests/goldens/plan-generator.cgtest
  src/tools/tests/plan-generator-tests.ts
  src/tools/tests/recipe2plan-codegen-test-suite.ts
Labels: cla: yes

#5810 Removed AbstractActiveStore
  src/runtime/storage/abstract-store.ts
  src/runtime/storage/storage.ts
  src/runtime/storage/store-interface.ts
  src/runtime/storage/store.ts
  src/runtime/tests/arc-test.ts
Labels: cla: yes

#5800 Remove `lifecycle` from ServiceStore API
  java/arcs/android/demo/BUILD
  java/arcs/android/demo/DemoActivity.kt
  java/arcs/android/host/prod/ProdArcHostService.kt
  java/arcs/android/sdk/host/AndroidHost.kt
  java/arcs/core/storage/ActiveStore.kt
  java/arcs/core/storage/DirectStore.kt
  java/arcs/core/storage/StoreManager.kt
  java/arcs/sdk/android/storage/ServiceStore.kt
  javatests/arcs/android/e2e/testapp/BUILD
  javatests/arcs/android/e2e/testapp/StorageAccessService.kt
  javatests/arcs/android/e2e/testapp/TestActivity.kt
  javatests/arcs/android/entity/BUILD
  javatests/arcs/android/entity/DifferentAndroidHandleManagerDifferentStoresTest.kt
  javatests/arcs/android/entity/DifferentHandleManagerTest.kt
  javatests/arcs/android/entity/SameHandleManagerTest.kt
  javatests/arcs/android/host/AndroidEntityHandleManagerTest.kt
  javatests/arcs/android/host/BUILD
  javatests/arcs/android/host/TestExternalArcHostService.kt
  javatests/arcs/android/host/TestProdArcHostService.kt
  javatests/arcs/android/systemhealth/testapp/BUILD
  javatests/arcs/android/systemhealth/testapp/LocalService.kt
  javatests/arcs/android/systemhealth/testapp/RemoteService.kt
  javatests/arcs/android/systemhealth/testapp/StorageCore.kt
  javatests/arcs/android/systemhealth/testapp/TestActivity.kt
  javatests/arcs/core/entity/DifferentHandleManagerDifferentStoresTest.kt
  javatests/arcs/sdk/android/storage/BUILD
  javatests/arcs/showcase/BUILD
  javatests/arcs/showcase/ShowcaseEnvironment.kt
  javatests/arcs/showcase/references/BUILD
Labels: cla: yes

#5857 Singleton variable fix
  java/arcs/core/entity/Handle.kt
  src/tools/kotlin-type-generator.ts
  src/tools/tests/goldens/plan-generator-handleConnections.cgtest
Labels: cla: yes

#5855 Fix type checking for ordered lists of schemas.
  src/runtime/manifest.ts
  src/runtime/schema.ts
  src/runtime/tests/type-checker-test.ts
Labels: cla: yes

#5856 Deletes policy EgressType enums and allows it to be an arbitrary string
  java/arcs/core/data/proto/policy.proto
  java/arcs/core/data/testdata/Manifest2ProtoTest.pb.bin
  java/arcs/core/data/testdata/Manifest2ProtoTest.textproto
  java/arcs/core/policy/Policy.kt
  java/arcs/core/policy/proto/PolicyProto.kt
  javatests/arcs/core/policy/PolicyConstraintsTest.kt
  javatests/arcs/core/policy/PolicyTest.kt
  javatests/arcs/core/policy/proto/PolicyConstraintsProtoTest.kt
  javatests/arcs/core/policy/proto/PolicyProtoTest.kt
  src/runtime/policy/canonical-policy-annotations.ts
  src/runtime/policy/policy.ts
  src/runtime/policy/tests/policy-test.ts
  src/tools/manifest-proto.ts
  src/tools/policy2proto.ts
  src/tools/tests/policy2proto-test.ts
Labels: cla: yes

#5818 Allow multiple instances of particles in recipes
  java/arcs/core/host/AbstractArcHost.kt
  java/arcs/core/host/ArcHostContext.kt
  java/arcs/core/host/ArcHostContextParticle.kt
  javatests/arcs/android/e2e/testapp/WriteAnimalHostService.kt
  javatests/arcs/core/allocator/AllocatorTestBase.kt
  javatests/arcs/core/host/AbstractArcHostTest.kt
  javatests/arcs/core/host/TestingHost.kt
  javatests/arcs/core/host/person.arcs
  javatests/arcs/showcase/ShowcaseEnvironment.kt
Labels: cla: yes

#5799 Tweaks to restore basic DevShell and SmokeShell functionality
  shells/dev-shell/store-panel.js
  shells/smoke-shell/app.js
  shells/smoke-shell/smoke.html
  shells/smoke-shell/smoke.js
  src/runtime/runtime.ts
Labels: cla: yes

#5787 Add DevToolsStorageManager
  java/arcs/android/devtools/BUILD
  java/arcs/android/devtools/DevToolsService.kt
  java/arcs/android/devtools/DevWebServerImpl.kt
  java/arcs/android/devtools/IDevToolsService.aidl
  java/arcs/android/devtools/storage/BUILD
  java/arcs/android/devtools/storage/DevToolsStorageConnection.kt
  java/arcs/android/storage/service/DevToolsStorageManager.kt
  java/arcs/android/storage/service/IDevToolsStorageManager.aidl
  java/arcs/sdk/android/storage/service/StorageService.kt
Labels: cla: yes

#5861 Add note about dereference workaround
  javatests/arcs/showcase/references/Reader.kt
Labels: cla: yes

#5853 Introduce a `HandleManager` interface
  java/arcs/core/host/AbstractArcHost.kt
  java/arcs/core/host/ArcHostContext.kt
  java/arcs/core/host/ArcHostContextParticle.kt
  java/arcs/core/host/EntityHandleManager.kt
  java/arcs/core/host/HandleManager.kt
  javatests/arcs/core/host/TestingHost.kt
Labels: cla: yes

#5850 Implements FROM, SELECT, WHERE, NEW
  java/arcs/core/data/expression/Builders.kt
  java/arcs/core/data/expression/Evaluator.kt
  java/arcs/core/data/expression/Expression.kt
  java/arcs/core/data/expression/RawEntityScope.kt
  java/arcs/core/data/expression/Serializer.kt
  java/arcs/core/data/expression/Stringifier.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
  javatests/arcs/core/entity/HandleManagerTestBase.kt
  src/tools/kotlin-refinement-generator.ts
  src/tools/tests/goldens/generated-schemas.jvm.kt
  src/tools/tests/goldens/kotlin-refinement-generator.cgtest
  src/tools/tests/goldens/kotlin-schema-generation.cgtest
  src/tools/tests/goldens/kt_generated-schemas.jvm.kt
  src/tools/tests/goldens/plan-generator-handleConnections.cgtest
  src/tools/tests/goldens/plan-generator-handles.cgtest
Labels: cla: yes

#5862 Lint warning for .only left in tests
  tools/local-presubmit
  tools/sigh.ts
Labels: cla: yes

#5846 Wrap EntityType and ReferenceType into SingletonType
  src/tools/kotlin-type-generator.ts
  src/tools/plan-generator.ts
  src/tools/tests/codegen-unit-tests-updater.ts
  src/tools/tests/goldens/WriterReaderExample.kt
  src/tools/tests/goldens/plan-generator-handles.cgtest
  src/tools/tests/goldens/plan-generator-plans.cgtest
Labels: cla: yes

#5863 Remove old references
  src/runtime/manifest-parser.pegjs
  src/runtime/tests/manifest-parser-test.ts
  src/tools/vscode-language-client/syntax/grammar.json
Labels: cla: yes

#5868 add paxel now() expression
  java/arcs/core/data/expression/BUILD
  java/arcs/core/data/expression/Builders.kt
  java/arcs/core/data/expression/Evaluator.kt
  java/arcs/core/util/BUILD
  java/arcs/core/util/PlatformTime.kt
  java/arcs/core/util/platform/js/PlatformTimeProvider.kt
  java/arcs/core/util/platform/jvm/PlatformTimeProvider.kt
  java/arcs/core/util/platform/native/PlatformTimeProvider.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
  src/tools/kotlin-refinement-generator.ts
Labels: cla: yes

#5848 Make arcs_sdk_deps to be an explicit argument to skylark macros
  third_party/java/arcs/build_defs/build_defs.bzl
  third_party/java/arcs/build_defs/internal/kotlin.bzl
  third_party/java/arcs/build_defs/internal/schemas.bzl
Labels: cla: yes

#5847 Use restricted Schema to serialize EntityBase
  java/arcs/core/entity/Entity.kt
  java/arcs/core/entity/EntityBase.kt
  java/arcs/core/entity/StorageAdapter.kt
  java/arcs/core/entity/VariableEntityBase.kt
  java/arcs/core/host/EntityHandleManager.kt
  javatests/arcs/core/entity/HandleManagerTestBase.kt
  javatests/arcs/core/entity/StorageAdapterTest.kt
Labels: cla: yes

#5871 Moves Particle Unit Testing example to Showcase
  javatests/arcs/showcase/unittesting/BUILD
  javatests/arcs/showcase/unittesting/ComputePeopleStatsTest.kt
Labels: cla: yes

#5836 Parser updated to support Max Type Variables (`~a with {*}`)
  src/runtime/manifest-parser.pegjs
  src/runtime/manifest.ts
  src/runtime/tests/manifest-parser-test.ts
  src/runtime/tests/manifest-test.ts
  src/runtime/tests/type-checker-test.ts
Labels: cla: yes

#5809 Creating a CLI + build rules for Recipe2Plan (take 2)
  java/arcs/core/data/testdata/BUILD
  java/arcs/tools/BUILD
  java/arcs/tools/README.md
  java/arcs/tools/Recipe2Plan.kt
  third_party/java/arcs/build_defs/build_defs.bzl
  third_party/java/arcs/build_defs/internal/plan.bzl
  third_party/java/arcs/build_defs/native.oss.bzl
Labels: cla: yes

#5866 Remove use of runBlocking in StorageService
  java/arcs/android/storage/service/BindingContext.kt
  java/arcs/android/storage/service/BindingContextStats.kt
Labels: cla: yes

#5852 More performant collection handle createReference() impl
  java/arcs/core/entity/CollectionHandle.kt
  java/arcs/core/entity/StorageAdapter.kt
Labels: cla: yes

#5869 Allow referring to policies from imported .arcs files
  src/runtime/manifest.ts
  src/runtime/tests/manifest-test.ts
Labels: cla: yes

#5874 Revert "Creating a CLI + build rules for Recipe2Plan (take 2) (#5809)"
  java/arcs/core/data/testdata/BUILD
  java/arcs/tools/BUILD
  java/arcs/tools/README.md
  java/arcs/tools/Recipe2Plan.kt
  third_party/java/arcs/build_defs/build_defs.bzl
  third_party/java/arcs/build_defs/internal/plan.bzl
  third_party/java/arcs/build_defs/native.oss.bzl
Labels: cla: yes

#5796 Remove the channel from `ServiceStore`
  java/arcs/sdk/android/storage/ServiceStore.kt
Labels: cla: yes

#5864 Update PolicyVerifier to use the new `@policy` recipe annotation.
  java/arcs/core/analysis/PolicyVerifier.kt
  java/arcs/core/data/Recipe.kt
  java/arcs/core/policy/PolicyConstraints.kt
  java/arcs/core/policy/PolicyOptions.kt
  javatests/arcs/core/analysis/BUILD
  javatests/arcs/core/analysis/PolicyVerifierTest.kt
  javatests/arcs/core/analysis/testdata/policy_test.arcs
  javatests/arcs/core/policy/PolicyConstraintsTest.kt
Labels: cla: yes

#5875 Fixes up the unit testing showcase
  java/arcs/sdk/examples/testing/BUILD
  javatests/arcs/showcase/unittesting/BUILD
  javatests/arcs/showcase/unittesting/ComputePeopleStats.arcs
  javatests/arcs/showcase/unittesting/ComputePeopleStats.kt
  javatests/arcs/showcase/unittesting/ComputePeopleStatsTest.kt
Labels: cla: yes

#5865 Devtools proxy
  java/arcs/android/devtools/DevToolsService.kt
  java/arcs/android/devtools/DevWebServerImpl.kt
  java/arcs/android/storage/service/BindingContext.kt
  java/arcs/android/storage/service/DevToolsProxyImpl.kt
  java/arcs/android/storage/service/DevToolsStorageManager.kt
  java/arcs/android/storage/service/IDevToolsProxy.aidl
  java/arcs/android/storage/service/IDevToolsStorageManager.aidl
  java/arcs/sdk/android/storage/service/StorageService.kt
  javatests/arcs/android/storage/service/BindingContextTest.kt
Labels: cla: yes

#5872 Asynchronous ArcHostContext serializations
  java/arcs/core/host/AbstractArcHost.kt
Labels: cla: yes

#5879 Clean up backing store type in in RefModeStore
  java/arcs/core/storage/ReferenceModeStore.kt
  javatests/arcs/core/storage/ReferenceModeStoreDatabaseIntegrationTest.kt
  javatests/arcs/core/storage/ReferenceModeStoreTest.kt
Labels: cla: yes

#5880 Merges type variables by name across all type containers
  src/runtime/tests/type-test.ts
  src/runtime/type.ts
Labels: cla: yes

#5876 Define PolicyOptionsProto with encode/decode functions
  java/arcs/core/data/proto/policy.proto
  java/arcs/core/policy/proto/PolicyOptionsProto.kt
  javatests/arcs/core/policy/proto/PolicyOptionsProtoTest.kt
Labels: cla: yes

#5884 Fix build deps
  java/arcs/android/devtools/storage/BUILD
Labels: cla: yes

#5839 Enable WAL on main database
  java/arcs/android/storage/database/DatabaseImpl.kt
  javatests/arcs/android/storage/database/DatabaseDowngradeTest.kt
Labels: cla: yes

#5885 more devtools deps fixes
  java/arcs/android/devtools/BUILD
Labels: cla: yes

#5887 Create a build_test automatically for jvm and android kt libraries
  third_party/java/arcs/build_defs/internal/kotlin.bzl
  third_party/java/arcs/build_defs/internal/util.bzl
  tools/build_defs/build_test/BUILD
  tools/build_defs/build_test/build_test.bzl
Labels: cla: yes

#5870 Wrap various calls to sigh_command in new macros in tools.oss.bzl
  src/tests/BUILD
  src/tools/tests/BUILD
  src/wasm/tests/BUILD
  third_party/java/arcs/build_defs/arcs_ts_test.bzl
  third_party/java/arcs/build_defs/build_defs.bzl
  third_party/java/arcs/build_defs/internal/kotlin.bzl
  third_party/java/arcs/build_defs/internal/manifest.bzl
  third_party/java/arcs/build_defs/internal/schemas.bzl
  third_party/java/arcs/build_defs/internal/tools.oss.bzl
Labels: cla: yes

#5849 Expedite entity queries from database while initializing handles at Arc startup
  java/arcs/android/storage/database/DatabaseImpl.kt
Labels: cla: yes

#5881 Optimize size queries of collection handles
  java/arcs/core/entity/CollectionHandle.kt
Labels: cla: yes

#5877 Delete `manifestChecker` / `arcs_manifest_parse_test`
  java/arcs/android/demo/BUILD
  particles/PipeApps/BUILD
  src/tools/manifest-checker.ts
  third_party/java/arcs/build_defs/build_defs.bzl
  third_party/java/arcs/build_defs/internal/tools.oss.bzl
  tools/sigh.ts
Labels: cla: yes

#5886 when merging crdtentities, check if the otherChange is empty. This wa…
  java/arcs/core/crdt/CrdtEntity.kt
  java/arcs/jvm/storage/database/testutil/FakeDatabaseManager.kt
  javatests/arcs/core/crdt/CrdtEntityTest.kt
  javatests/arcs/core/storage/ReferenceModeStoreDatabaseIntegrationTest.kt
Labels: cla: yes

#5888 Delete manifest2json
  src/tools/manifest2json.ts
  src/wasm/tests/BUILD
  third_party/java/arcs/build_defs/build_defs.bzl
  third_party/java/arcs/build_defs/internal/manifest.bzl
  third_party/java/arcs/build_defs/internal/tools.oss.bzl
  tools/sigh.ts
Labels: cla: yes

#5843 DFA: Handle inline entities, lists and tuple fields properly.
  java/arcs/core/analysis/InformationFlow.kt
  javatests/arcs/core/analysis/InformationFlowTest.kt
  javatests/arcs/core/analysis/testdata/fail_field_entity_ref_field.arcs
  javatests/arcs/core/analysis/testdata/fail_field_inline_entity_direct.arcs
  javatests/arcs/core/analysis/testdata/fail_field_inline_entity_slicing.arcs
  javatests/arcs/core/analysis/testdata/fail_field_list_direct.arcs
  javatests/arcs/core/analysis/testdata/fail_field_tuple_direct.arcs
  javatests/arcs/core/analysis/testdata/ok_field_entity_ref_field.arcs
  javatests/arcs/core/analysis/testdata/ok_field_inline_entity_direct.arcs
  javatests/arcs/core/analysis/testdata/ok_field_inline_entity_slicing.arcs
  javatests/arcs/core/analysis/testdata/ok_field_list_direct.arcs
  javatests/arcs/core/analysis/testdata/ok_field_tuple_direct.arcs
Labels: cla: yes

#5873 Change expression from String to Expression
  java/arcs/android/host/parcelables/ParcelableHandleConnection.kt
  java/arcs/core/data/Plan.kt
  java/arcs/core/data/Recipe.kt
  java/arcs/core/host/ArcHostContextParticle.kt
  java/arcs/core/host/BUILD
  javatests/arcs/android/host/parcelables/BUILD
  javatests/arcs/android/host/parcelables/ParcelableHandleConnectionTest.kt
  javatests/arcs/core/data/BUILD
  javatests/arcs/core/data/RecipeTest.kt
Labels: cla: yes

#5854 Introduce the new `StorageEndpointManager` interface
  java/arcs/core/host/EntityHandleManager.kt
  java/arcs/core/host/StorageEndpointManager.kt
  java/arcs/core/storage/ActiveStore.kt
  java/arcs/core/storage/BUILD
  java/arcs/core/storage/ProxyInterface.kt
  java/arcs/core/storage/StorageProxy.kt
  java/arcs/core/storage/api/BUILD
  javatests/arcs/core/storage/StorageProxyTest.kt
  javatests/arcs/core/storage/StoreEndpointFake.kt
Labels: cla: yes

#5904 Remove compilation warnings from DevTools/e2e TestApp
  java/arcs/android/devtools/DevToolsService.kt
  java/arcs/android/storage/service/DevToolsProxyImpl.kt
  java/arcs/android/storage/service/DevToolsStorageManager.kt
  java/arcs/sdk/android/storage/service/StorageService.kt
  javatests/arcs/android/e2e/testapp/StorageAccessService.kt
Labels: cla: yes

#5897 Remove deprecated `EntityHandleManager` constructor.
  java/arcs/core/host/AbstractArcHost.kt
  java/arcs/core/host/EntityHandleManager.kt
Labels: cla: yes

#5899 Remove unused, deprecated ServiceStore constructor
  java/arcs/sdk/android/storage/BUILD
  java/arcs/sdk/android/storage/ServiceStore.kt
Labels: cla: yes

#5896 Remove unused, deprecated Scheduler methods
  java/arcs/core/util/Scheduler.kt
Labels: cla: yes

#5890 Support type variables in data flow analysis.
  java/arcs/core/analysis/InformationFlow.kt
  javatests/arcs/core/analysis/InformationFlowTest.kt
  javatests/arcs/core/analysis/testdata/fail_type_variables.arcs
  javatests/arcs/core/analysis/testdata/fail_type_variables_collection.arcs
  javatests/arcs/core/analysis/testdata/fail_type_variables_multiple_constraints.arcs
  javatests/arcs/core/analysis/testdata/fail_type_variables_tuples.arcs
  javatests/arcs/core/analysis/testdata/fail_type_variables_tuples_collection.arcs
  javatests/arcs/core/analysis/testdata/policy_test.arcs
Labels: cla: yes

#5893 Encoding / Decoding Max Type Variables via Protos
  java/arcs/core/data/TypeVariable.kt
  java/arcs/core/data/proto/TypeProtoDecoders.kt
  java/arcs/core/data/proto/manifest.proto
  javatests/arcs/core/data/TypeVariableTest.kt
  javatests/arcs/core/data/proto/TypeProtoDecodersTest.kt
  src/tools/manifest2proto.ts
  src/tools/tests/manifest2proto-test.ts
  src/tools/tests/recipe2plan-test.ts
Labels: cla: yes

#5889 Creates the VerifyPolicy tool to check policy compliance in manifests
  java/arcs/tools/BUILD
  java/arcs/tools/VerifyPolicy.kt
  third_party/java/arcs/build_defs/native.oss.bzl
Labels: cla: yes

#5900 Remove unused `activationFactory` parameter from ArcHosts.
  java/arcs/android/demo/DemoService.kt
  java/arcs/android/host/prod/ProdArcHostService.kt
  java/arcs/android/sdk/host/AndroidHost.kt
  java/arcs/android/sdk/host/AndroidResurrectableHost.kt
  java/arcs/core/host/AbstractArcHost.kt
  javatests/arcs/android/e2e/testapp/PersonHostService.kt
  javatests/arcs/android/e2e/testapp/ReadAnimalHostService.kt
  javatests/arcs/android/e2e/testapp/WriteAnimalHostService.kt
  javatests/arcs/showcase/ShowcaseEnvironment.kt
Labels: cla: yes

#5907 Temporarily restore runBlocking until flakey tests are fixed
  java/arcs/android/storage/service/BindingContext.kt
Labels: cla: yes

#5903 Create RawDevToolsMessage
  java/arcs/android/devtools/DevToolsMessage.kt
  java/arcs/android/devtools/DevToolsService.kt
  java/arcs/android/devtools/RawDevToolsMessage.kt
Labels: cla: yes

#5909 make ttl test size medium, as it can very rarely timeout otherwise se…
  javatests/arcs/android/storage/ttl/BUILD
Labels: cla: yes

#5901 Fix some warnings
  java/arcs/android/devtools/DevToolsService.kt
  java/arcs/android/storage/service/DevToolsProxyImpl.kt
  javatests/arcs/android/storage/ReferenceModeStoreDatabaseImplIntegrationTest.kt
  javatests/arcs/core/storage/ReferenceModeStoreDatabaseIntegrationTest.kt
  javatests/arcs/showcase/ShowcaseEnvironment.kt
Labels: cla: yes

#5914 Restore immediate acknowledgement of sendProxyMessage
  java/arcs/android/storage/service/BindingContext.kt
Labels: cla: yes

#5916 Fixes for devtools errors
  java/arcs/android/devtools/DevToolsService.kt
Labels: cla: yes

#5895 Remove defaults for `AbstractArcHost`'s `CoroutineContext` params
  java/arcs/android/demo/DemoService.kt
  java/arcs/android/host/prod/ProdArcHostService.kt
  java/arcs/android/sdk/host/AndroidHost.kt
  java/arcs/android/sdk/host/AndroidResurrectableHost.kt
  java/arcs/android/sdk/host/BUILD
  java/arcs/core/host/AbstractArcHost.kt
  java/arcs/jvm/host/JvmHost.kt
  javatests/arcs/android/e2e/testapp/PersonHostService.kt
  javatests/arcs/android/e2e/testapp/ReadAnimalHostService.kt
  javatests/arcs/android/e2e/testapp/WriteAnimalHostService.kt
  javatests/arcs/android/host/AndroidAllocatorTest.kt
  javatests/arcs/android/host/TestProdArcHostService.kt
  javatests/arcs/core/host/AbstractArcHostTest.kt
  javatests/arcs/core/host/BUILD
  javatests/arcs/core/host/ParticleRegistrationTest.kt
  javatests/arcs/core/host/ReflectiveParticleConstructionTest.kt
  javatests/arcs/core/host/TestHost.kt
  javatests/arcs/core/host/TestingHost.kt
  javatests/arcs/showcase/ShowcaseEnvironment.kt
Labels: cla: yes

#5921 Make an inline variant of references showcase
  javatests/arcs/showcase/inline/ArcsStorage.kt
  javatests/arcs/showcase/inline/BUILD
  javatests/arcs/showcase/inline/Items.kt
  javatests/arcs/showcase/inline/ReadWriteTest.kt
  javatests/arcs/showcase/inline/Reader.kt
  javatests/arcs/showcase/inline/Writer.kt
  javatests/arcs/showcase/inline/schema.arcs
Labels: cla: yes

#5923 Removes a DB check for empty entity ID for inline entities.
  java/arcs/android/storage/database/DatabaseImpl.kt
Labels: cla: yes

#5917 Fixing "Unused Java BUILD Deps" issues.
  java/arcs/android/sdk/host/BUILD
  java/arcs/android/type/BUILD
  java/arcs/core/storage/BUILD
  java/arcs/core/storage/api/BUILD
  java/arcs/core/storage/util/BUILD
  java/arcs/core/type/BUILD
  java/arcs/sdk/android/storage/BUILD
  javatests/arcs/core/host/BUILD
Labels: cla: yes

#5924 Use strings for the `when` helper in hot.ts to catch mismatching case lengths
  src/runtime/hot.ts
  src/runtime/tests/hot-test.ts
Labels: cla: yes

#5902 Rewrite dot only check to work on GCB (without .git)
  tools/sigh.ts
Labels: cla: yes

#5925 Unit test dirs should be named 'tests'
  src/runtime/testing/tests/sequence-test.ts
Labels: cla: yes

#5926 Type Variable showcase supports checks, claims, and with {*}
  javatests/arcs/showcase/typevariables/Consumer.kt
  javatests/arcs/showcase/typevariables/variable.arcs
Labels: cla: yes

#5922 Rework ingress restricting to rely on Type system for dropping unread fields
  java/arcs/core/data/testdata/WriterReaderExample.arcs
  src/runtime/capabilities-resolver.ts
  src/runtime/manifest.ts
  src/runtime/policy/ingress-validation.ts
  src/runtime/policy/policy.ts
  src/runtime/policy/tests/ingress-validation-test.ts
  src/runtime/recipe/handle.ts
  src/runtime/recipe/recipe-resolver.ts
  src/runtime/schema.ts
  src/runtime/tests/schema-test.ts
  src/runtime/type.ts
  src/tools/allocator-recipe-resolver.ts
  src/tools/plan-generator.ts
  src/tools/recipe2plan.ts
  src/tools/tests/Variable.arcs
  src/tools/tests/VariablePlanTest.kt
  src/tools/tests/allocator-recipe-resolver-test.ts
  src/tools/tests/goldens/WriterReaderExample.kt
  src/tools/tests/goldens/plan-generator-handleConnections.cgtest
  src/tools/tests/plan-generator-tests.ts
  src/tools/tests/recipe2plan-codegen-test-suite.ts
  src/tools/tests/recipe2plan-test.ts
Labels: cla: yes

#5927 WIP Add applicaitonInfo.flags
  java/arcs/sdk/android/storage/service/StorageService.kt
Labels: cla: yes

#5912 Update VerifyPolicy tool to accept .textproto PolicyOptions files
  java/arcs/core/data/proto/BUILD
  java/arcs/core/policy/proto/BUILD
  java/arcs/tools/BUILD
  java/arcs/tools/VerifyPolicy.kt
Labels: cla: yes

#5939 Revert "Rework ingress restricting to rely on Type system for droppin…
  java/arcs/core/data/testdata/WriterReaderExample.arcs
  src/runtime/capabilities-resolver.ts
  src/runtime/manifest.ts
  src/runtime/policy/ingress-validation.ts
  src/runtime/policy/policy.ts
  src/runtime/policy/tests/ingress-validation-test.ts
  src/runtime/recipe/handle.ts
  src/runtime/recipe/recipe-resolver.ts
  src/runtime/schema.ts
  src/runtime/tests/schema-test.ts
  src/runtime/type.ts
  src/tools/allocator-recipe-resolver.ts
  src/tools/plan-generator.ts
  src/tools/recipe2plan.ts
  src/tools/tests/Variable.arcs
  src/tools/tests/VariablePlanTest.kt
  src/tools/tests/allocator-recipe-resolver-test.ts
  src/tools/tests/goldens/WriterReaderExample.kt
  src/tools/tests/goldens/plan-generator-handleConnections.cgtest
  src/tools/tests/plan-generator-tests.ts
  src/tools/tests/recipe2plan-codegen-test-suite.ts
  src/tools/tests/recipe2plan-test.ts
Labels: cla: yes

#5911 Defines a run_test helper BUILD rule and policy_test for manifest files
  javatests/arcs/tools/BUILD
  javatests/arcs/tools/options.textproto
  javatests/arcs/tools/policy_testcase.arcs
  particles/Native/Wasm/BUILD
  third_party/bazel_skylib/lib/BUILD
  third_party/bazel_skylib/lib/shell.bzl
  third_party/java/arcs/build_defs/internal/manifest.bzl
  third_party/java/arcs/build_defs/internal/run_test.bzl
  third_party/java/arcs/build_defs/internal/schemas.bzl
  third_party/java/arcs/build_defs/internal/tools.oss.bzl
Labels: cla: yes

#5932 Fail manifest2proto when imports are missing
  src/tools/manifest2proto.ts
Labels: cla: yes

#5931 Move particle-spec to src/runtime/manifest-types
  src/dataflow/analysis/particle-node.ts
  src/planning/plan/suggestion.ts
  src/planning/recipe-index.ts
  src/planning/strategies/coalesce-recipes.ts
  src/planning/strategies/convert-constraints-to-connections.ts
  src/planning/strategies/create-description-handle.ts
  src/planning/strategies/find-hosted-particle.ts
  src/planning/strategies/group-handle-connections.ts
  src/planning/strategies/map-slots.ts
  src/planning/strategies/match-recipe-by-verb.ts
  src/platform/loader-base.ts
  src/runtime/api-channel.ts
  src/runtime/arc-serializer.ts
  src/runtime/arc.ts
  src/runtime/claim.ts
  src/runtime/description-formatter.ts
  src/runtime/interface-info-impl.ts
  src/runtime/manifest-types/particle-spec.ts
  src/runtime/manifest.ts
  src/runtime/particle-execution-context.ts
  src/runtime/particle.ts
  src/runtime/recipe/connection-constraint.ts
  src/runtime/recipe/handle-connection.ts
  src/runtime/recipe/handle.ts
  src/runtime/recipe/particle.ts
  src/runtime/recipe/recipe-resolver.ts
  src/runtime/recipe/recipe-util.ts
  src/runtime/recipe/recipe-walker.ts
  src/runtime/recipe/recipe.ts
  src/runtime/recipe/slot-connection.ts
  src/runtime/recipe/slot-utils.ts
  src/runtime/slot-composer.ts
  src/runtime/storage/handle.ts
  src/runtime/storage/storage.ts
  src/runtime/tests/manifest-test.ts
  src/runtime/tests/particle-interface-loading-test.ts
  src/runtime/type.ts
  src/runtime/ui-multiplexer-particle.ts
  src/tools/kotlin-type-generator.ts
  src/tools/manifest2proto.ts
  src/tools/schema2base.ts
  src/tools/schema2cpp.ts
  src/tools/schema2graph.ts
  src/tools/schema2kotlin.ts
  src/tools/tests/schema2wasm-test.ts
Labels: cla: yes

#5930 Move Direction enum to new enums file in manifest-types
  src/planning/strategies/convert-constraints-to-connections.ts
  src/planning/strategies/match-recipe-by-verb.ts
  src/runtime/check.ts
  src/runtime/manifest-ast-nodes.ts
  src/runtime/manifest-types/enums.ts
  src/runtime/manifest-types/particle-spec.ts
  src/runtime/recipe/connection-constraint.ts
  src/runtime/recipe/direction-util.ts
  src/runtime/recipe/handle-connection.ts
  src/runtime/recipe/handle.ts
  src/runtime/recipe/recipe-util.ts
  src/runtime/recipe/recipe.ts
  src/runtime/recipe/type-checker.ts
  src/runtime/type.ts
  src/tools/plan-generator.ts
  src/tools/schema2kotlin.ts
Labels: cla: yes

#5933 DFA: Handle type variables with no constraints appropriately.
  java/arcs/core/analysis/InformationFlow.kt
  javatests/arcs/core/analysis/InformationFlowTest.kt
  javatests/arcs/core/analysis/testdata/fail_type_variables_no_constraints.arcs
Labels: cla: yes

#5935 Propagate Plan.Handle's schema to StorageAdapter
  java/arcs/core/entity/EntityBase.kt
  java/arcs/core/entity/StorageAdapter.kt
  java/arcs/core/host/AbstractArcHost.kt
  java/arcs/core/host/EntityHandleManager.kt
  java/arcs/core/host/HandleManager.kt
  javatests/arcs/core/entity/RestrictedDummyEntity.kt
  javatests/arcs/core/entity/StorageAdapterTest.kt
  javatests/arcs/core/host/AbstractArcHostTest.kt
  javatests/arcs/showcase/typevariables/variable.arcs
Labels: cla: yes

#5940 Revert "Revert "Rework ingress restricting to rely on Type system for droppin…"
  java/arcs/core/data/testdata/WriterReaderExample.arcs
  src/runtime/capabilities-resolver.ts
  src/runtime/manifest.ts
  src/runtime/policy/ingress-validation.ts
  src/runtime/policy/policy.ts
  src/runtime/policy/tests/ingress-validation-test.ts
  src/runtime/recipe/handle.ts
  src/runtime/recipe/recipe-resolver.ts
  src/runtime/schema.ts
  src/runtime/tests/schema-test.ts
  src/runtime/type.ts
  src/tools/allocator-recipe-resolver.ts
  src/tools/plan-generator.ts
  src/tools/recipe2plan.ts
  src/tools/tests/Variable.arcs
  src/tools/tests/VariablePlanTest.kt
  src/tools/tests/allocator-recipe-resolver-test.ts
  src/tools/tests/goldens/WriterReaderExample.kt
  src/tools/tests/goldens/plan-generator-handleConnections.cgtest
  src/tools/tests/plan-generator-tests.ts
  src/tools/tests/recipe2plan-codegen-test-suite.ts
  src/tools/tests/recipe2plan-test.ts
Labels: cla: yes

#5908 Improve Arcs startup by tuning idle debouncing
  java/arcs/core/host/AbstractArcHost.kt
  java/arcs/core/util/Scheduler.kt
  java/arcs/jvm/host/JvmSchedulerProvider.kt
  javatests/arcs/android/systemhealth/testapp/TestSchedulerProvider.kt
Labels: cla: yes

#5918 Quicken DirectStoreMuxer.idle
  java/arcs/core/storage/DirectStore.kt
  java/arcs/core/storage/DirectStoreMuxer.kt
Labels: cla: yes

#5928 Fix deadlock at DirectStore.close
  java/arcs/core/storage/BUILD
  java/arcs/core/storage/DirectStore.kt
  java/arcs/core/storage/DirectStoreMuxer.kt
  java/arcs/core/storage/ReferenceModeStore.kt
  java/arcs/core/storage/StoreInterface.kt
  java/arcs/sdk/android/storage/service/StorageService.kt
Labels: cla: yes

#5934 If a protected store is not marked, policy verifier rejects recipes.
  java/arcs/core/analysis/PolicyVerifier.kt
  javatests/arcs/core/analysis/PolicyVerifierTest.kt
  javatests/arcs/core/analysis/testdata/policy_test.arcs
Labels: cla: yes

#5920 Simplify coroutine logic in DatabaseManagers
  java/arcs/android/storage/database/AndroidSqliteDatabaseManager.kt
  java/arcs/android/storage/database/DatabaseGarbageCollectionPeriodicTask.kt
  java/arcs/android/storage/ttl/PeriodicCleanupTask.kt
  java/arcs/core/storage/database/DatabaseManager.kt
  java/arcs/jvm/storage/database/testutil/FakeDatabaseManager.kt
  javatests/arcs/android/entity/TtlHandleTest.kt
Labels: cla: yes

#5941 Extract DatabaseData to CRDT Data helper functions
  java/arcs/core/storage/driver/Database.kt
Labels: cla: yes

#5946 Move modality.ts and slot-direction enum into manifest-types.
  src/planning/plan/suggestion.ts
  src/planning/plan/tests/plan-consumer-test.ts
  src/planning/recipe-index.ts
  src/planning/strategies/tests/convert-constraints-to-connections-test.ts
  src/planning/strategies/tests/match-particle-by-verb-test.ts
  src/planning/testing/strategy-test-helper.ts
  src/runtime/arc.ts
  src/runtime/manifest-ast-nodes.ts
  src/runtime/manifest-types/enums.ts
  src/runtime/manifest-types/modality.ts
  src/runtime/manifest-types/particle-spec.ts
  src/runtime/recipe/recipe.ts
  src/runtime/runtime.ts
  src/runtime/slot-composer.ts
  src/runtime/tests/recipe-test.ts
  src/runtime/type.ts
Labels: cla: yes

#5947 move check.ts and claim.ts into manifest-types
  src/dataflow/analysis/flow-graph.ts
  src/dataflow/analysis/graph-internals.ts
  src/dataflow/analysis/particle-node.ts
  src/dataflow/analysis/testing/flow-graph-testing.ts
  src/dataflow/analysis/tests/graph-internals-test.ts
  src/runtime/manifest-ast-nodes.ts
  src/runtime/manifest-parser.pegjs
  src/runtime/manifest-types/check.ts
  src/runtime/manifest-types/claim.ts
  src/runtime/manifest-types/enums.ts
  src/runtime/manifest-types/particle-spec.ts
  src/runtime/manifest.ts
  src/runtime/storage/abstract-store.ts
  src/runtime/tests/manifest-test.ts
  src/tools/manifest2proto.ts
  tools/sigh.ts
Labels: cla: yes

#5936 Lazy Plans
  src/tools/kotlin-generation-utils.ts
  src/tools/plan-generator.ts
  src/tools/tests/codegen-unit-tests-runner-test.ts
  src/tools/tests/goldens/WriterReaderExample.kt
  src/tools/tests/goldens/plan-generator-handles.cgtest
  src/tools/tests/goldens/plan-generator-plans.cgtest
  src/tools/tests/kotlin-generation-utils-test.ts
  src/tools/tests/recipe2plan-test.ts
Labels: cla: yes

#5942 Clarify StorageKeyParser interface, make global instance thread-safe
  java/arcs/android/demo/DemoApplication.kt
  java/arcs/android/host/parcelables/BUILD
  java/arcs/core/data/CreatableStorageKey.kt
  java/arcs/core/storage/StorageKey.kt
  java/arcs/core/storage/StorageKeyParser.kt
  java/arcs/core/storage/api/DriverAndKeyConfigurator.kt
  java/arcs/core/storage/driver/Database.kt
  java/arcs/core/storage/keys/DatabaseStorageKey.kt
  java/arcs/core/storage/keys/JoinStorageKey.kt
  java/arcs/core/storage/keys/RamDiskStorageKey.kt
  java/arcs/core/storage/keys/VolatileStorageKey.kt
  java/arcs/core/storage/referencemode/ReferenceModeStorageKey.kt
  java/arcs/core/storage/testutil/DummyStorageKey.kt
  java/arcs/sdk/android/storage/ResurrectionHelper.kt
  java/arcs/sdk/storage/StorageKey.kt
  javatests/arcs/android/common/resurrection/ResurrectionRequestTest.kt
  javatests/arcs/android/common/resurrection/ResurrectorServiceTest.kt
  javatests/arcs/android/crdt/BUILD
  javatests/arcs/android/crdt/ReferenceProtoTest.kt
  javatests/arcs/android/e2e/testapp/TestApplication.kt
  javatests/arcs/android/host/parcelables/BUILD
  javatests/arcs/android/host/parcelables/ParcelableHandleConnectionTest.kt
  javatests/arcs/android/host/parcelables/ParcelableHandleTest.kt
  javatests/arcs/android/host/parcelables/ParcelableParticleTest.kt
  javatests/arcs/android/host/parcelables/ParcelablePlanPartitionTest.kt
  javatests/arcs/android/host/parcelables/ParcelablePlanTest.kt
  javatests/arcs/android/storage/ParcelableStoreOptionsTest.kt
  javatests/arcs/android/storage/ReferenceModeStoreDatabaseImplIntegrationTest.kt
  javatests/arcs/android/storage/database/AndroidSqliteDatabaseManagerTest.kt
  javatests/arcs/android/storage/database/DatabaseImplTest.kt
  javatests/arcs/core/storage/StorageKeyParserTest.kt
  javatests/arcs/core/storage/keys/DatabaseStorageKeyTest.kt
  javatests/arcs/core/storage/keys/JoinStorageKeyTest.kt
  javatests/arcs/core/storage/keys/RamDiskStorageKeyTest.kt
  javatests/arcs/core/storage/keys/VolatileStorageKeyTest.kt
  javatests/arcs/core/storage/referencemode/ReferenceModeStorageKeyTest.kt
  javatests/arcs/sdk/HandleUtilsTest.kt
  javatests/arcs/sdk/android/storage/ResurrectionHelperTest.kt
  javatests/arcs/sdk/android/storage/service/StorageServiceTest.kt
Labels: cla: yes

#5919 Bazel rules for Kotlin Recipe2plan implementation
  java/arcs/core/data/testdata/BUILD
  java/arcs/tools/BUILD
  java/arcs/tools/README.md
  java/arcs/tools/Recipe2Plan.kt
  third_party/java/arcs/build_defs/build_defs.bzl
  third_party/java/arcs/build_defs/internal/kotlin.bzl
  third_party/java/arcs/build_defs/internal/plan.bzl
  third_party/java/arcs/build_defs/internal/tools.oss.bzl
Labels: cla: yes, timezonegame

#5952 Adds some helper methods for Result
  java/arcs/core/data/proto/ManifestProtoDecoder.kt
  java/arcs/core/data/proto/ParticleSpecProtoDecoder.kt
  java/arcs/core/util/Result.kt
  javatests/arcs/core/data/proto/ParticleSpecProtoDecoderTest.kt
Labels: cla: yes

#5953 Fix bug with clearing all data with inline entities in the database
  java/arcs/android/storage/database/DatabaseImpl.kt
  javatests/arcs/android/storage/database/AndroidSqliteDatabaseManagerTest.kt
  javatests/arcs/android/storage/database/DatabaseGarbageCollectionPeriodicTaskTest.kt
  javatests/arcs/android/storage/service/StorageServiceManagerTest.kt
  javatests/arcs/android/storage/ttl/PeriodicCleanupTaskTest.kt
Labels: cla: yes

#5955 Fix removal of entities: inline entites do not have entity_refs entri…
  java/arcs/android/storage/database/DatabaseImpl.kt
  javatests/arcs/android/storage/ttl/PeriodicCleanupTaskTest.kt
Labels: cla: yes

#5956 Update TestBase to be Kotlin/Native 1.4 compatible.
  javatests/arcs/sdk/wasm/TestBase.kt
Labels: cla: yes

#5961 Renames the generated ManifestProto target from foo_manifest_proto to foo_proto
  third_party/java/arcs/build_defs/internal/manifest.bzl
Labels: cla: yes

#5960 Fix race where processModelUpdate can be called after close()
  java/arcs/core/storage/StorageProxy.kt
Labels: cla: yes

#5964 Ensure inline entities are also deleted when a parent entity is.
  java/arcs/android/storage/database/DatabaseImpl.kt
  javatests/arcs/android/storage/database/DatabaseImplTest.kt
Labels: cla: yes

#5959 Include fetchById in CollectionHandle
  java/arcs/core/entity/CollectionHandle.kt
  java/arcs/core/entity/Handle.kt
  java/arcs/core/testutil/handles/HandleHelpers.kt
  javatests/arcs/core/entity/HandleManagerTestBase.kt
  javatests/arcs/showcase/references/Reader.kt
Labels: cla: yes

#5915 Introduce simpler `SchedulerProvider`
  java/arcs/android/demo/DemoActivity.kt
  java/arcs/android/demo/DemoService.kt
  java/arcs/core/host/SimpleSchedulerProvider.kt
  java/arcs/jvm/host/JvmRoundRobinSchedulerProvider.kt
  java/arcs/sdk/testing/BaseTestHarness.kt
  javatests/arcs/android/e2e/testapp/PersonHostService.kt
  javatests/arcs/android/e2e/testapp/ReadAnimalHostService.kt
  javatests/arcs/android/e2e/testapp/TestActivity.kt
  javatests/arcs/android/e2e/testapp/WriteAnimalHostService.kt
  javatests/arcs/android/entity/DifferentAndroidHandleManagerDifferentStoresTest.kt
  javatests/arcs/android/entity/DifferentHandleManagerTest.kt
  javatests/arcs/android/entity/SameHandleManagerTest.kt
  javatests/arcs/android/entity/TtlHandleTest.kt
  javatests/arcs/android/host/AndroidEntityHandleManagerTest.kt
  javatests/arcs/android/host/TestExternalArcHostService.kt
  javatests/arcs/android/host/TestProdArcHostService.kt
  javatests/arcs/android/host/TestReadingExternalHostService.kt
  javatests/arcs/android/host/TestWritingExternalHostService.kt
  javatests/arcs/android/storage/database/DatabaseGarbageCollectionPeriodicTaskTest.kt
  javatests/arcs/android/storage/service/StorageServiceManagerTest.kt
  javatests/arcs/android/storage/ttl/PeriodicCleanupTaskTest.kt
  javatests/arcs/android/systemhealth/testapp/TestActivity.kt
  javatests/arcs/core/allocator/AllocatorTestBase.kt
  javatests/arcs/core/entity/DifferentHandleManagerDifferentStoresTest.kt
  javatests/arcs/core/entity/DifferentHandleManagerTest.kt
  javatests/arcs/core/entity/HandleManagerCloseTest.kt
  javatests/arcs/core/entity/HandleManagerTestBase.kt
  javatests/arcs/core/entity/SameHandleManagerTest.kt
  javatests/arcs/core/host/AbstractArcHostTest.kt
  javatests/arcs/core/host/ArcHostManagerTest.kt
  javatests/arcs/core/host/HandleAdapterTest.kt
  javatests/arcs/core/host/LifecycleTest.kt
  javatests/arcs/core/host/ParticleRegistrationTest.kt
  javatests/arcs/core/host/ReflectiveParticleConstructionTest.kt
  javatests/arcs/core/host/SimpleSchedulerProviderTest.kt
  javatests/arcs/jvm/host/JvmRoundRobinSchedulerProviderTest.kt
  javatests/arcs/showcase/ShowcaseEnvironment.kt
Labels: cla: yes

#5966 Fix: Duplicate inline entities cause schema2graph cyclic dependency issue
  src/tools/schema2graph.ts
  src/tools/tests/schema2graph-test.ts
Labels: cla: yes

#5957 Make DevToolsService run in the foreground
  java/arcs/android/devtools/AndroidManifest.xml
  java/arcs/android/devtools/BUILD
  java/arcs/android/devtools/DevToolsService.kt
  java/arcs/android/devtools/res/drawable/devtools_icon.png
  javatests/arcs/android/e2e/testapp/AndroidManifest.xml
  javatests/arcs/android/e2e/testapp/TestActivity.kt
Labels: cla: yes

#5967 Set size of core HandleMangerTests to 'medium'
  javatests/arcs/core/entity/BUILD
Labels: cla: yes

#5965 Add legacy multi-dex configuration to testapp
  javatests/arcs/android/systemhealth/testapp/BUILD
  javatests/arcs/android/systemhealth/testapp/mainDexClasses.rules
Labels: cla: yes

#5971 Propagate the `size` param in arcs_kt_jvm_test_suite
  third_party/java/arcs/build_defs/internal/kotlin.bzl
Labels: cla: yes

#5970 Remove useless parentheses from bzl files.
  third_party/java/arcs/build_defs/internal/kotlin.bzl
  third_party/java/arcs/build_defs/internal/schemas.bzl
Labels: cla: yes

#5963 fix race in StorageWriteBackTest
  java/arcs/jvm/storage/database/testutil/FakeDatabaseManager.kt
Labels: cla: yes

#5972 syshealth app: support memory database
  javatests/arcs/android/systemhealth/testapp/StorageCore.kt
  javatests/arcs/android/systemhealth/testapp/TestActivity.kt
  javatests/arcs/android/systemhealth/testapp/TestEntity.kt
  javatests/arcs/android/systemhealth/testapp/res/layout/test_activity.xml
  javatests/arcs/android/systemhealth/testapp/res/values/strings.xml
Labels: cla: yes

#5969 syshealth app: support inline entities
  javatests/arcs/android/systemhealth/testapp/StorageCore.kt
  javatests/arcs/android/systemhealth/testapp/TestActivity.kt
  javatests/arcs/android/systemhealth/testapp/TestApplication.kt
  javatests/arcs/android/systemhealth/testapp/TestEntity.kt
Labels: cla: yes

#5913 Refactor cpp files in Native/Wasm folder for simple copybara config.
  particles/Native/Wasm/Kotlin/BUILD
  particles/Native/Wasm/Kotlin/Harness.arcs
  particles/Native/Wasm/Kotlin/ServiceParticle.kt
  particles/Native/Wasm/Kotlin/Services.arcs
  particles/Native/Wasm/Kotlin/TestParticle.kt
  particles/Native/Wasm/cpp/BUILD
  particles/Native/Wasm/cpp/example.arcs
  particles/Native/Wasm/cpp/example.cc
  particles/Native/Wasm/wasm.arcs
Labels: cla: yes

#5950 Remove `storageKey` from `StorageKeyParser` exception messages
  java/arcs/core/data/CreatableStorageKey.kt
  java/arcs/core/storage/StorageKeyParser.kt
  java/arcs/core/storage/keys/DatabaseStorageKey.kt
  java/arcs/core/storage/keys/JoinStorageKey.kt
  java/arcs/core/storage/keys/RamDiskStorageKey.kt
  java/arcs/core/storage/keys/VolatileStorageKey.kt
  java/arcs/core/storage/referencemode/ReferenceModeStorageKey.kt
Labels: cla: yes

#5980 A small bugfix to Paxel aggregation functions
  java/arcs/core/data/expression/Evaluator.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
Labels: cla: yes

#5977 Cleans up a comment about optional fields
  src/tools/schema2kotlin.ts
  src/tools/tests/goldens/generated-schemas.jvm.kt
  src/tools/tests/goldens/generated-schemas.wasm.kt
  src/tools/tests/goldens/generated-test-harness.kt
  src/tools/tests/goldens/kt_generated-schemas.jvm.kt
Labels: cla: yes

#5981 Make Particle Test Harness more flexible
  javatests/arcs/sdk/testing/BaseTestHarnessTest.kt
  src/tools/schema2kotlin.ts
  src/tools/tests/goldens/generated-test-harness.kt
  src/tools/tests/goldens/kotlin-test-harness.cgtest
Labels: cla: yes

#5975 Derive binary manifest proto file name from BUILD target name
  javatests/arcs/core/analysis/InformationFlowTest.kt
  javatests/arcs/core/analysis/PolicyVerifierTest.kt
  javatests/arcs/core/analysis/RecipeGraphToDotGraphTest.kt
  third_party/java/arcs/build_defs/internal/manifest.bzl
Labels: cla: yes

#5976 Define a new allowed-packages-tools package group for using Arcs CLI tools
  java/arcs/BUILD
  java/arcs/tools/BUILD
Labels: cla: yes

#5983 Make STORAGE_CLASS a const val
  java/arcs/android/devtools/DevToolsService.kt
Labels: cla: yes

#5984 Particle Evaluating Paxel Expressions
  java/arcs/core/data/expression/BUILD
  java/arcs/core/data/expression/EvaluatorParticle.kt
  javatests/arcs/core/data/expression/BUILD
  javatests/arcs/core/data/expression/EvaluatorParticleTest.kt
  javatests/arcs/core/data/expression/Particles.arcs
  src/tools/plan-generator.ts
Labels: cla: yes

#5958 Updating sigh to use new manifest-ast-nodes path.
  tools/sigh.ts
Labels: cla: yes

#5994 Move and rename `runtime/manifest-string-builder.ts` to `utils/indenting-string-builder.ts`
  src/dataflow/analysis/analysis.ts
  src/runtime/arc-serializer.ts
  src/runtime/arcs-types/particle-spec.ts
  src/runtime/interface-info-impl.ts
  src/runtime/policy/policy.ts
  src/runtime/recipe/annotation.ts
  src/runtime/schema.ts
  src/runtime/storage/abstract-store.ts
  src/runtime/type.ts
  src/utils/indenting-string-builder.ts
  src/utils/tests/indenting-string-builder-test.ts
Labels: cla: yes

#5992 Standardize timeouts in StorageServiceManagerTest. With this the test…
  javatests/arcs/android/storage/service/StorageServiceManagerTest.kt
Labels: cla: yes

#5954 Fix a bug with GC in databases.
  javatests/arcs/android/storage/service/BUILD
  javatests/arcs/android/storage/service/StorageServiceEndToEndTest.kt
Labels: cla: yes

#5986 Adds a new `@ingress` particle annotation
  java/arcs/core/analysis/PolicyVerifier.kt
  java/arcs/core/data/Annotation.kt
  java/arcs/core/data/ParticleSpec.kt
  javatests/arcs/core/data/ParticleSpecTest.kt
  src/runtime/arcs-types/particle-spec.ts
  src/runtime/canonical-manifest.ts
  src/runtime/tests/manifest-test.ts
Labels: cla: yes

#5995 Start moving recipe/ dependencies to a new lib-recipe.ts.
  src/dataflow/analysis/analysis.ts
  src/dataflow/analysis/flow-graph.ts
  src/dataflow/analysis/handle-node.ts
  src/dataflow/analysis/particle-node.ts
  src/dataflow/analysis/slot-node.ts
  src/runtime/arcs-types/enums.ts
  src/runtime/manifest-ast-types/enums.ts
  src/runtime/manifest-ast-types/manifest-ast-nodes.ts
  src/runtime/recipe/lib-recipe.ts
Labels: cla: yes

#5998 Remove placeholders in DevToolsNG simple interface.
  devtoolsNG/basic/index.html
Labels: cla: yes

#5990 A change that should not affect copy bara import.
  third_party/java/arcs/build_defs/arcs_ts_test.bzl
Labels: cla: yes, ready to pull

#5991 A github PR with changes that should be imported and skipped.
  java/arcs/core/analysis/AccessPathLabels.kt
  third_party/java/arcs/build_defs/arcs_ts_test.bzl
Labels: cla: yes, ready to pull

#6004 Quick fix for nested froms in Paxel
  java/arcs/core/data/expression/Builders.kt
  java/arcs/core/data/expression/Evaluator.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
Labels: cla: yes

#6001 Uses the `@ingress` annotation to identify ingress handles.
  java/arcs/core/analysis/BUILD
  java/arcs/core/analysis/PolicyVerifier.kt
  java/arcs/core/data/proto/AccessPathProtoDecoder.kt
  java/arcs/core/data/proto/manifest.proto
  java/arcs/core/policy/PolicyConstraints.kt
  java/arcs/core/policy/proto/PolicyConstraintsProto.kt
  javatests/arcs/core/analysis/PolicyVerifierTest.kt
  javatests/arcs/core/analysis/testdata/policy_test.arcs
  javatests/arcs/core/policy/PolicyConstraintsTest.kt
  javatests/arcs/core/policy/proto/PolicyConstraintsProtoTest.kt
Labels: cla: yes

#6009 Return to runBlocking for callback registration
  java/arcs/android/storage/service/BindingContext.kt
Labels: cla: yes

#6005 Showcase for Paxel particles
  java/arcs/core/data/Plan.kt
  javatests/arcs/showcase/expression/BUILD
  javatests/arcs/showcase/expression/ExpressionShowcaseTest.kt
  javatests/arcs/showcase/expression/expression.arcs
Labels: cla: yes

#6000 allocator-recipe-resolver supports mapping manifest stores
  src/runtime/type.ts
  src/tools/allocator-recipe-resolver.ts
  src/tools/tests/allocator-recipe-resolver-test.ts
Labels: cla: yes

#5982 Move Type.toSchema() to TypeUtil.kt in core/data
  java/arcs/core/analysis/BUILD
  java/arcs/core/analysis/PolicyVerifier.kt
  java/arcs/core/data/TypeUtil.kt
  java/arcs/core/data/expression/BUILD
  java/arcs/core/data/expression/EvaluatorParticle.kt
  java/arcs/core/host/Utils.kt
  javatests/arcs/core/host/TestReflectiveParticle.kt
  src/tools/tests/VariablePlanTest.kt
Labels: cla: yes

#6007 change FROM to use expression sources
  java/arcs/core/data/expression/Builders.kt
  java/arcs/core/data/expression/Evaluator.kt
  java/arcs/core/data/expression/Expression.kt
  java/arcs/core/data/expression/Serializer.kt
  java/arcs/core/data/expression/Stringifier.kt
  javatests/arcs/core/data/expression/EvaluatorParticleTest.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
Labels: cla: yes

#6010 Use dispatcher methods for fetch and fetchById in tests
  javatests/arcs/core/entity/HandleManagerTestBase.kt
  javatests/arcs/core/host/AbstractArcHostTest.kt
Labels: cla: yes

#6021 fix infinite loop
  java/arcs/core/data/expression/Serializer.kt
Labels: cla: yes

#6020 Fixes Paxel showcase after string->expression migration in from clause
  javatests/arcs/showcase/expression/ExpressionShowcaseTest.kt
Labels: cla: yes

#6012 Deletes PolicyOptions, it's not needed anymore.
  java/arcs/core/analysis/PolicyVerifier.kt
  java/arcs/core/data/proto/policy.proto
  java/arcs/core/policy/PolicyConstraints.kt
  java/arcs/core/policy/PolicyOptions.kt
  java/arcs/core/policy/proto/PolicyOptionsProto.kt
  java/arcs/tools/VerifyPolicy.kt
  javatests/arcs/core/policy/PolicyConstraintsTest.kt
  javatests/arcs/core/policy/proto/PolicyOptionsProtoTest.kt
  javatests/arcs/tools/BUILD
  javatests/arcs/tools/options.textproto
  third_party/java/arcs/build_defs/internal/manifest.bzl
  third_party/java/arcs/build_defs/internal/tools.oss.bzl
Labels: cla: yes

#6018 Adjustments for nested 'from a in b'
  java/arcs/core/data/expression/Evaluator.kt
  javatests/arcs/core/data/expression/ExpressionTest.kt
Labels: cla: yes

#5985 Add a getEntityCount() method to Database.
  java/arcs/android/storage/database/DatabaseImpl.kt
  java/arcs/core/storage/database/Database.kt
  java/arcs/jvm/storage/database/testutil/FakeDatabaseManager.kt
  javatests/arcs/android/storage/database/DatabaseImplTest.kt
Labels: cla: yes

#6024 Move arc-planner-invoker .. and, like, 90% of everything else .. to start using lib-recipe.ts
  src/devtools-connector/arc-planner-invoker.ts
  src/devtools-connector/hot-code-reloader.ts
  src/planning/plan/suggestion.ts
  src/planning/plan/tests/planning-result-test.ts
  src/planning/planner.ts
  src/planning/recipe-index.ts
  src/planning/speculator.ts
  src/planning/strategies/add-missing-handles.ts
  src/planning/strategies/coalesce-recipes.ts
  src/planning/strategies/convert-constraints-to-connections.ts
  src/planning/strategies/create-handle-group.ts
  src/planning/strategies/find-required-particle.ts
  src/planning/strategies/group-handle-connections.ts
  src/planning/strategies/init-population.ts
  src/planning/strategies/init-search.ts
  src/planning/strategies/match-free-handles-to-connections.ts
  src/planning/strategies/match-recipe-by-verb.ts
  src/planning/strategies/tests/convert-constraints-to-connections-test.ts
  src/planning/strategies/tests/match-particle-by-verb-test.ts
  src/planning/strategizer.ts
  src/runtime/api-channel.ts
  src/runtime/arc-inspector.ts
  src/runtime/arc-serializer.ts
  src/runtime/arc.ts
  src/runtime/description-formatter.ts
  src/runtime/description.ts
  src/runtime/manifest.ts
  src/runtime/particle-execution-host.ts
  src/runtime/policy/ingress-validation.ts
  src/runtime/policy/tests/ingress-validation-test.ts
  src/runtime/recipe/connection-constraint.ts
  src/runtime/recipe/constraint-walker.ts
  src/runtime/recipe/handle-connection.ts
  src/runtime/recipe/handle.ts
  src/runtime/recipe/lib-recipe.ts
  src/runtime/recipe/particle.ts
  src/runtime/recipe/recipe-resolver.ts
  src/runtime/recipe/recipe-util.ts
  src/runtime/recipe/recipe-walker.ts
  src/runtime/recipe/recipe.ts
  src/runtime/recipe/search.ts
  src/runtime/recipe/slot-connection.ts
  src/runtime/recipe/slot-utils.ts
  src/runtime/recipe/slot.ts
  src/runtime/relevance.ts
  src/runtime/runtime.ts
  src/runtime/slot-composer.ts
  src/runtime/tests/description-test.ts
  src/runtime/tests/particle-interface-loading-with-slots-test.ts
  src/runtime/tests/recipe-test.ts
  src/runtime/tests/type-test.ts
  src/tools/allocator-recipe-resolver.ts
  src/tools/kotlin-type-generator.ts
  src/tools/manifest2proto.ts
  src/tools/plan-generator.ts
  src/tools/tests/plan-generator-tests.ts
Labels: cla: yes

#6003 Add getSize() to Database which returns the size of the database in b…
  java/arcs/android/storage/database/DatabaseImpl.kt
  java/arcs/core/storage/database/Database.kt
  java/arcs/jvm/storage/database/testutil/FakeDatabaseManager.kt
  javatests/arcs/android/storage/database/DatabaseImplTest.kt
Labels: cla: yes

#6025 Remove remaining references to recipe/* files (where feasible).
  src/devtools-connector/devtools-arc-inspector.ts
  src/planning/plan/tests/suggestion-test.ts
  src/planning/strategies/create-description-handle.ts
  src/planning/strategies/create-handle-group.ts
  src/planning/strategies/find-hosted-particle.ts
  src/planning/strategies/map-slots.ts
  src/planning/strategies/match-particle-by-verb.ts
  src/planning/strategies/name-unnamed-connections.ts
  src/planning/strategies/search-tokens-to-particles.ts
  src/planning/strategies/tests/create-handle-group-test.ts
  src/planning/strategies/tests/rulesets-test.ts
  src/runtime/interface-info-impl.ts
  src/runtime/tests/particle-interface-loading-test.ts
  src/runtime/tests/recipe-util-test.ts
  src/runtime/tests/recipe/search-test.ts
  src/runtime/tests/type-checker-test.ts
  src/tests/recipe-descriptions-test.ts
  src/tools/allocator-recipe-resolver.ts
Labels: cla: yes

#6011 Move crdt files into a src-level module
  src/crdt/internal/crdt-collection.ts
  src/crdt/internal/crdt-count.ts
  src/crdt/internal/crdt-entity.ts
  src/crdt/internal/crdt-singleton.ts
  src/crdt/internal/crdt.ts
  src/crdt/internal/tests/crdt-collection-test.ts
  src/crdt/internal/tests/crdt-count-test.ts
  src/crdt/internal/tests/crdt-entity-test.ts
  src/crdt/internal/tests/crdt-singleton-test.ts
  src/crdt/lib-crdt.ts
  src/runtime/api-channel.ts
  src/runtime/particle-execution-context.ts
  src/runtime/particle-execution-host.ts
  src/runtime/particle.ts
  src/runtime/reference.ts
  src/runtime/schema.ts
  src/runtime/storage/abstract-store.ts
  src/runtime/storage/direct-store-muxer.ts
  src/runtime/storage/direct-store.ts
  src/runtime/storage/handle.ts
  src/runtime/storage/reference-mode-store.ts
  src/runtime/storage/storage-proxy-muxer.ts
  src/runtime/storage/storage-proxy.ts
  src/runtime/storage/storage.ts
  src/runtime/storage/store-interface.ts
  src/runtime/storage/store.ts
  src/runtime/storage/testing/test-storage.ts
  src/runtime/storage/tests/direct-store-muxer-test.ts
  src/runtime/storage/tests/entity-handle-factory-test.ts
  src/runtime/storage/tests/firebase-store-integration-test.ts
  src/runtime/storage/tests/handle-test.ts
  src/runtime/storage/tests/ramdisk-direct-store-muxer-integration-test.ts
  src/runtime/storage/tests/ramdisk-store-integration-test.ts
  src/runtime/storage/tests/reference-mode-store-test.ts
  src/runtime/storage/tests/storage-proxy-muxer-test.ts
  src/runtime/storage/tests/storage-proxy-test.ts
  src/runtime/storage/tests/store-sequence-test.ts
  src/runtime/storage/tests/store-test.ts
  src/runtime/testing/identity.ts
  src/runtime/tests/arc-test.ts
  src/runtime/type.ts
  src/runtime/ui-multiplexer-particle.ts
  src/runtime/ui-particle-base.ts
  src/runtime/ui-particle.ts
  src/runtime/wasm.ts
Labels: cla: yes

#6023 followup for #6000: add types to var declarations in allocator-recipe-resolver
  src/tools/allocator-recipe-resolver.ts
Labels: cla: yes

#5996 Remove deprecated `EntityHandleManager` constructor.
  java/arcs/core/host/EntityHandleManager.kt
Labels: cla: yes

#6017 Update README for DevToolsNG
  README.md
  devtoolsNG/README.md
Labels: cla: yes

#6032 Add restrictType to Handle Interface in recipe-lib.ts
  src/runtime/recipe/lib-recipe.ts
Labels: cla: yes

#6038 Increases size of ReferenceModeStoreDatabaseImplIntegrationTest test …
  javatests/arcs/android/storage/BUILD
Labels: cla: yes
